<<<<<<< HEAD
---
title: "HLC_SB_Analysis"
author: "Alissa Iverson"
date: "7/14/2022"
output: html_document
---

```{r libraries, bring in file, some data cleaning}
#using format of CA's veg code and trying to make it work for the sb, wish me luck 
library(knitr); library(multcomp); library(dplyr);library(lme4);library(ggplot2); library(tidyverse); library(tidytext);
library(ggpubr); library(rstatix);library(writexl);library(ggformula); library(tidyr);library(reshape2); library(sjPlot); library(emmeans)
library(lmerTest)

#Bring in raw data file

#Import data using a relative pathway


seedbank <- read.csv("20220802_HLC_SB_Data_Final5.csv") #mac path


#Turquoise path

seedbank <- seedbank %>%
  mutate(Transect_ID = as.factor(Transect_ID)) %>%
  mutate(Baseline = as.factor(Baseline)) 


#head(seedbank)
#str(seedbank)

#View(seedbank)

#Rename unwieldly columns; remove unwanted columns
# "-" means to drop that variable
#seedbankdf <- seedbank %>% select(c(-Specific.Epithet_wconservative.cf, -Org_trayID))
seedbankdf <- seedbank %>% select(c(-Specific.Epithet_wconservative.cf))

#changed name of column
seedbankdf <- seedbankdf %>% rename(c(Species_Name=SPECIFIC_EPITHET_FINAL, Germinant_ID_Number = Germinant.ID))

#The old code: vegdf <- veg_sp %>% select(-Number.of.Points.Along.Transect_fromRick) %>%
#rename(Num_transect_points = Number.of.points.along.transect_ChrissyCalc)

#head(seedbankdf)
#View(seedbankdf)

#check species spellings

df_sb <- seedbankdf %>% distinct(Species_Name)

#View(df_sb)
#^Looks good, not sure if I should keep or remove unknowns? 


#Pull out species names using "distinct"; arrange alphabetically using "arrange";remove 
#unwanted entries (rock, soil, litter) using "subset"; keep desired columns using "select"
df_Spp <- distinct(seedbankdf, Species_Name, .keep_all = TRUE) %>%
  arrange(Species_Name)%>%
  subset(Species_Name!="Unknown" & Species_Name!="Unknown forb"
         & Species_Name!="Unknown graminoid" & Species_Name!= "Unknown Poaceae") %>%
  select(Species_Name, Bank_Location, Longevity_1, Habit, Functional_Group_2, Nativity, WIS)

#view(df_Spp)
#write_xlsx(df_Spp, 'SB_SppList.xlsx')


```

```{r create species tables}

#View(df_Spp)

#Export to Excel
#write_xlsx(df_Spp, 'SB_SpeciesList_V2_AI_08202022.xlsx') 


SB_Spp_tbl <- seedbankdf %>%
  select(Species_Name, Longevity_1, Habit, Nativity, WIS)%>% 
  group_by(Species_Name, Longevity_1, Habit, Nativity, WIS) %>%
  summarise(Freq2 = n())

SB_Spp_prop_tbl <- SB_Spp_tbl %>%
  drop_na(Species_Name) %>%
  mutate(prop = Freq2/sum(SB_Spp_tbl$Freq2))

view(SB_Spp_prop_tbl)
sum(SB_Spp_prop_tbl$Freq2)
#write_xlsx(SB_Spp_prop_tbl, 'SB_SppList_Proportions.xlsx')

#merge with veg prop data

#veg_prop_tbl <- read.csv("./Veg_SppList_Prop4_AI08202022.csv")
veg_prop_tbl <- read.csv("AG_SppList_proportions_2023.csv")
#^need to update with new AG file 1/17/23

merged_spp_prop <- merge(veg_prop_tbl, SB_Spp_prop_tbl, by.x = c("VegHit_SoilSurfaceHit", "Longevity", "Habit", "WIS_GP", "Nativity"), by.y = c("Species_Name", "Longevity_1", "Habit", "WIS", "Nativity"), all.x =TRUE, all.y = TRUE)

view(merged_spp_prop)

write_xlsx(merged_spp_prop, 'merged_SppList_Prop_2023.xlsx')


#Merged but seperated by Bank Location
#Lower
SB_Spp_tbl_Lower <- seedbankdf %>%
  filter(Bank_Location == "Lower") %>%
  select(Species_Name, Longevity_1, Habit, Nativity, WIS)%>% 
  group_by(Species_Name, Longevity_1, Habit, Nativity, WIS) %>%
  summarise(Freq2 = n())
view(SB_Spp_tbl_Lower)

SB_Spp_prop_tbl_Lower <- SB_Spp_tbl_Lower %>%
  drop_na(Species_Name) %>%
  mutate(prop = Freq2/sum(SB_Spp_tbl_Lower$Freq2))

view(SB_Spp_prop_tbl_Lower)
sum(SB_Spp_prop_tbl_Lower$Freq2)
#write_xlsx(SB_Spp_prop_tbl, 'SB_SppList_Proportions.xlsx')

#merge with veg prop data, lower

veg_prop_tbl_lower <- read.csv("AG_SppList_proportions_Lower.csv")
view(veg_prop_tbl_lower)


merged_spp_prop_lower <- merge(veg_prop_tbl_lower, SB_Spp_prop_tbl_Lower, by.x = c("VegHit_SoilSurfaceHit", "Longevity", "Habit", "WIS_GP", "Nativity"), by.y = c("Species_Name", "Longevity_1", "Habit", "WIS", "Nativity"), all.x =TRUE, all.y = TRUE)

view(merged_spp_prop_lower)

write_xlsx(merged_spp_prop_lower, 'merged_SppList_Prop_lower.xlsx')

#Middle
SB_Spp_tbl_Middle <- seedbankdf %>%
  filter(Bank_Location == "Middle") %>%
  select(Species_Name, Longevity_1, Habit, Nativity, WIS)%>% 
  group_by(Species_Name, Longevity_1, Habit, Nativity, WIS) %>%
  summarise(Freq2 = n())
view(SB_Spp_tbl_Middle)

SB_Spp_prop_tbl_Middle <- SB_Spp_tbl_Middle %>%
  drop_na(Species_Name) %>%
  mutate(prop = Freq2/sum(SB_Spp_tbl_Middle$Freq2))

view(SB_Spp_prop_tbl_Middle)
sum(SB_Spp_prop_tbl_Middle$Freq2)
#write_xlsx(SB_Spp_prop_tbl, 'SB_SppList_Proportions.xlsx')

#merge with veg prop data, middle

veg_prop_tbl_middle <- read.csv("AG_SppList_proportions_middle.csv")
view(veg_prop_tbl_middle)


merged_spp_prop_middle <- merge(veg_prop_tbl_middle, SB_Spp_prop_tbl_Middle, by.x = c("VegHit_SoilSurfaceHit", "Longevity", "Habit", "WIS_GP", "Nativity"), by.y = c("Species_Name", "Longevity_1", "Habit", "WIS", "Nativity"), all.x =TRUE, all.y = TRUE)

view(merged_spp_prop_middle)

write_xlsx(merged_spp_prop_middle, 'merged_SppList_Prop_middle.xlsx')


#Upper
SB_Spp_tbl_Upper <- seedbankdf %>%
  filter(Bank_Location == "Upper") %>%
  select(Species_Name, Longevity_1, Habit, Nativity, WIS)%>% 
  group_by(Species_Name, Longevity_1, Habit, Nativity, WIS) %>%
  summarise(Freq2 = n())
view(SB_Spp_tbl_Upper)

SB_Spp_prop_tbl_Upper <- SB_Spp_tbl_Upper %>%
  drop_na(Species_Name) %>%
  mutate(prop = Freq2/sum(SB_Spp_tbl_Upper$Freq2))

view(SB_Spp_prop_tbl_Upper)
sum(SB_Spp_prop_tbl_Upper$Freq2)
#write_xlsx(SB_Spp_prop_tbl, 'SB_SppList_Proportions.xlsx')

#merge with veg prop data, upper

veg_prop_tbl_upper <- read.csv("AG_SppList_proportions_Upper.csv")
view(veg_prop_tbl_upper)


merged_spp_prop_upper <- merge(veg_prop_tbl_upper, SB_Spp_prop_tbl_Upper, by.x = c("VegHit_SoilSurfaceHit", "Longevity", "Habit", "WIS_GP", "Nativity"), by.y = c("Species_Name", "Longevity_1", "Habit", "WIS", "Nativity"), all.x =TRUE, all.y = TRUE)

view(merged_spp_prop_upper)

write_xlsx(merged_spp_prop_upper, 'merged_SppList_Prop_upper.xlsx')

```

```{r count germinants at each level of organization: canal, baseline, transect, bank location}

#Summing number of germinants at each level of organization (whole canal, baselines, transects)
#For whole canal, no need to group by anything

germinants.canal <- seedbankdf %>%
  summarise(Species.Name = n()) 
view(germinants.canal)
#View(germinants.canal)
#write_xlsx(germinants.canal, 'germinants_byCanal.xlsx')

#Germinants by baseline

germinants.baseline <- seedbankdf %>% 
  group_by(Baseline) %>%
  summarise(Species.Name = n()) 

#View(germinants.baseline)

#families counted
SB_families <- seedbankdf %>% 
  group_by(Family) %>%
  summarise(Species.Name = n()) 

view(SB_families)

write_xlsx(SB_families, 'sb_fam_counts.xlsx')



#write_xlsx(germinants.baseline, 'germinants_byBaseline.xlsx')

#Germinants by transect

germinants.transect <- seedbankdf %>% 
  group_by(Transect_ID) %>%
  summarise(Species.Name = n()) 

#View(germinants.transect)

#write_xlsx(germinants.transect, 'germinants_bytransect.xlsx')

germinants.bankloc <- seedbankdf %>%
  group_by(Transect_ID, Bank_Location) %>%
  summarise(Species_Name = n())

#View(germinants.bankloc)



```




```{r WIS Graph}

#Prepping data to compute proportions
#By baseline and bank location
seedbankdf[seedbankdf == 'Juncus sp. (FACW-OBL)'] <- 'Juncus sp.*' #Changing name so it looks nicer in graph

#view(seedbank)
seedbankdf$WIS <- as.factor(seedbankdf$WIS)

df.props_WIS_seed <- seedbankdf %>%
  group_by(Baseline, Transect_ID, Bank_Location, WIS, Longevity_1, Habit, Functional_Group_1, Nativity) %>%
  drop_na(Species_Name, WIS) %>%  ## drops rows with missing values NA in either SPECIFIC_EPITHET_FINAL or WIS
  summarise(Species_Name = n()) %>%  ## from the group_by groupings, count the number 
  group_by(Baseline, Transect_ID, Bank_Location, WIS) %>% #added transect so I can get mean
  summarise(Species_Name = sum(Species_Name)) %>%  ## groups by baseline and Bank_location to sum SPECIFIC_EPITHET_FINAL
  mutate(prop = Species_Name/sum(Species_Name)) %>% ## mutate the df by adding prop that is each #sp/total
  complete(WIS, fill = list(Species_Name = 0, prop = 0)) ## keep all levels of factor and replace NA with zeros for both   SPECIFIC_EPITHET_FINAL and prop
#checkout color packages, ggplot color package

#view(df.props_WIS_seed)


# Check it adds to one with the 5 groups  
sum(df.props_WIS_seed$prop[1:5])
#view(df.props_WIS_seed)

#get the means across transect (transected is nested within baseline as replication)
df_WIS_means_sb <- df.props_WIS_seed %>%
  group_by(Baseline, Bank_Location, WIS) %>%
  dplyr::summarise(Mean = mean(prop))

#View(df_WIS_means_sb)

#get the means again but average bank location as well
df_WIS_means_sb2 <- df.props_WIS_seed %>%
  group_by(Baseline, WIS) %>%
  dplyr::summarise(Mean = mean(prop))
#View(df_WIS_means_sb2)


#Make boxplot

#boxplot without bank location
WIS <- df_WIS_means_sb2 %>% 
  mutate(WIS = fct_relevel(WIS, "UPL", 'FACU', 'FAC', 'FACW', 'OBL', 'Juncus sp.*')) %>% 
  ggplot(aes(x=factor(WIS), y=Mean, fill=WIS))+ 
  geom_boxplot()+
    geom_point()+
    labs(x = "Wetland Indicator Status", y = "Proportion of Seedbank")+
    stat_summary(fun=mean, geom="point", aes(group = WIS), position = position_dodge(.9), shape=20, size=2.5, color="orange", fill="orange")+
    theme_bw(base_size = 10)+
    theme(legend.position = "none", axis.text.x=element_text(angle=45, hjust=1))+
    scale_fill_brewer(palette = "BuPu")
print(WIS)



WIS_BL <- df_WIS_means_sb %>% 
  mutate(WIS = fct_relevel(WIS, "UPL", 'FACU', 'FAC', 'FACW', 'OBL', 'Juncus sp.*')) %>% 
  ggplot(aes(x=factor(WIS), y=Mean, fill=WIS))+ 
  geom_boxplot()+
    geom_point()+
    labs(x = "Wetland Indicator Status", y = "Proportion of Seedbank")+
    stat_summary(fun=mean, geom="point", aes(group = WIS), position = position_dodge(.9), shape=20, size=2.5, color="orange", fill="orange")+
    theme_bw(base_size = 10)+
    theme(legend.position = "none", axis.text.x=element_text(angle=45, hjust=1))+
    scale_fill_brewer(palette = "BuPu")
print(WIS_BL)

WIS_BL <- WIS_BL + facet_wrap(~Bank_Location) 
print(WIS_BL) 



#Make stacked bar graph 

df_stacked <- aggregate(Mean ~ Bank_Location + WIS , data = df_WIS_means_sb, FUN = mean)

View(df_stacked)

St_WIS <- df_stacked %>%
  mutate(WIS = fct_relevel(WIS, "UPL", 'FACU', 'FAC', 'FACW', 'OBL', 'Juncus sp.*')) %>%
  ggplot(aes(fill = WIS, y = Mean, x = Bank_Location))+
  geom_bar(position = "stack", stat = "identity", color = "black") +
  labs(x = "Bank Location", y = "Proportion of Seed Bank") +
  guides(fill = guide_legend("WIS")) +
  theme_bw(base_size = 16) +
  scale_fill_brewer(palette = "BuPu")

print(St_WIS)


#stacked graph for baseline

df_stacked_WIS_baseline_sb <- aggregate(prop ~ Baseline + WIS, data = df.props_WIS_seed, FUN = mean)

View(df_stacked_WIS_baseline_sb)

df_stacked_WIS_baseline_sb$Baseline <- as.character(df_stacked_WIS_baseline_sb$Baseline)

df_stacked_WIS_baseline_sb %>%
  mutate(WIS = fct_relevel(WIS, "UPL", 'FACU', 'FAC', 'FACW', 'OBL', 'Juncus sp.*')) %>%
  mutate(Baseline = fct_relevel(Baseline, "B3", "B5", "B7", "B10", "B13", "B14", "B15", "B17", "B18")) %>%
  ggplot(aes(fill = WIS, y = prop, x = Baseline))+
  geom_bar(position = "stack", stat = "identity", color = "black") +
  labs(x = "Baseline", y = "Proportion of Seed Bank") +
  guides(fill = guide_legend("WIS")) +
  theme_bw(base_size = 16)+
  scale_fill_brewer(palette = "BuPu")

```

```{r Functional Group Graph}

#Prepping data to compute proportions
#By baseline and bank location

#view(seedbank)

seedbank$Functional_Group_2 <- as.factor(seedbank$Functional_Group_2)

seedbank <- seedbank %>% rename(FunctionalGroup = Functional_Group_2)

#### try changing name of Functional group and then change all code belower

df.props_FunctGroup_seed <- seedbank %>%
   filter(FunctionalGroup !="Long-lived Woody") %>% #removing these groups from the graph (NAs were already dropped)
 filter(FunctionalGroup !="NA Forb") %>%
 filter(FunctionalGroup !="NA NA") %>%
 filter(FunctionalGroup !="NA Graminoid") %>%
 filter(FunctionalGroup !="  Graminoid") %>%
 filter(FunctionalGroup !="Variable Forb") %>%
  group_by(Baseline, Transect_ID, Bank_Location, WIS, Longevity_2, Habit, FunctionalGroup, Nativity) %>%
  drop_na(SPECIFIC_EPITHET_FINAL, Longevity_2, Habit, Nativity, FunctionalGroup) %>%  ## drops rows with missing values NA in either SPECIFIC_EPITHET_FINAL or WIS
  summarise(SPECIFIC_EPITHET_FINAL = n()) %>%  ## from the group_by groupings, count the number 
  group_by(Baseline, Transect_ID, Bank_Location, FunctionalGroup) %>% #added transect so I can get mean
  summarise(SPECIFIC_EPITHET_FINAL = sum(SPECIFIC_EPITHET_FINAL)) %>%  ## groups by baseline and Bank_location to sum SPECIFIC_EPITHET_FINAL
  mutate(prop = SPECIFIC_EPITHET_FINAL/sum(SPECIFIC_EPITHET_FINAL)) %>%## mutate the df by adding prop that is each #sp/total
  complete(FunctionalGroup, fill = list(SPECIFIC_EPITHET_FINAL = 0, prop = 0)) %>% ## keep all levels of factor and replace NA with zeros for both   SPECIFIC_EPITHET_FINAL and prop
 filter(FunctionalGroup !="Long-lived Woody") %>% #removing these groups from the graph (NAs were already dropped)
 filter(FunctionalGroup !="NA Forb") %>%
 filter(FunctionalGroup !="NA NA") %>%
 filter(FunctionalGroup !="NA Graminoid") %>%
 filter(FunctionalGroup !="  Graminoid") %>%
 filter(FunctionalGroup !="Variable Forb") # have to filter these out twice, due to complete function

#view(df.props_FunctGroup_seed)
#checkout color packages, ggplot color package
# Check it adds to one with the 5 groups  
sum(df.props_FunctGroup_seed$prop[1:4])
#get the means across transect (transected is nested within baseline as replication)

df_FGroup_means <- df.props_FunctGroup_seed %>%
  group_by(Baseline, Bank_Location, FunctionalGroup) %>%
  dplyr::summarise(Mean = mean(prop))

#View(df_FGroup_means)

#get the means again but average bank location as well
df_FGroup_means_sb2 <- df.props_FunctGroup_seed %>%
  group_by(Baseline, FunctionalGroup) %>%
  dplyr::summarise(Mean = mean(prop))
#View(df_FGroup_means_sb2)

#boxplot without bank location
FGroup1 <- df_FGroup_means_sb2 %>% 
  ggplot(aes(x=FunctionalGroup, y=Mean, fill=FunctionalGroup))+ 
  geom_boxplot()+
    geom_point()+
    labs(x = "Functional Group", y = "Proportion of Seed Bank")+
    stat_summary(fun=mean, geom="point", aes(group = FunctionalGroup), position = position_dodge(.9), shape=20, size=2.5, color="orange", fill="orange")+
    theme_bw(base_size = 10)+
    theme(legend.position = "none", axis.text.x=element_text(angle=45, hjust=1))+
    scale_fill_brewer(palette = "BuPu")
print(FGroup1)


#Make boxplot with means, look at bank location
FGroup2 <- df_FGroup_means %>% 
  ggplot(aes(x=FunctionalGroup, y=Mean, fill=FunctionalGroup))+ 
  geom_boxplot()+
    geom_point()+
    labs(x = "Functional Group", y = "Proportion of Seed Bank")+
    stat_summary(fun=mean, geom="point", aes(group = FunctionalGroup), position = position_dodge(.9), shape=20, size=2.5, color="orange", fill="orange")+
    theme_bw(base_size = 10)+
    theme(legend.position = "none", axis.text.x=element_text(angle=45, hjust=1))+
    scale_fill_brewer(palette = "BuPu")
print(FGroup2)
FGroup2_BL <- FGroup2 + facet_wrap(~Bank_Location)
print(FGroup2_BL)


#Make stacked bar graph 

FG_stacked <- aggregate(Mean ~ Bank_Location + FunctionalGroup , data = df_FGroup_means, FUN = mean)

#View(FG_stacked)

St_FG <- FG_stacked %>%
  ggplot(aes(fill = FunctionalGroup, y = Mean, x = Bank_Location))+
  geom_bar(position = "stack", stat = "identity", color = "black") +
  labs(x = "Bank Location", y = "Proportion of Seed bank") +
  guides(fill = guide_legend("Functional Group")) +
  theme_bw(base_size = 16) +
  scale_fill_brewer(palette = "BuPu")

print(St_FG)




```

```{r Nativity Graph}
#Prepping data to compute proportions
#By baseline and bank location

seedbank$Nativity <- as.factor(seedbank$Nativity)


df.props_nativity_sb <- seedbank %>%
  group_by(Baseline, Transect_ID, Bank_Location, WIS, Longevity_1, Habit, Functional_Group_1, Nativity) %>%
  drop_na(SPECIFIC_EPITHET_FINAL, WIS, Nativity) %>%  ## drops rows with missing values NA in either SPECIFIC_EPITHET_FINAL or WIS
  summarise(SPECIFIC_EPITHET_FINAL = n()) %>%  ## from the group_by groupings, count the number 
  group_by(Baseline, Transect_ID, Bank_Location, Nativity) %>% #added transect so I can get mean
  summarise(SPECIFIC_EPITHET_FINAL = sum(SPECIFIC_EPITHET_FINAL)) %>%  ## groups by baseline and Bank_location to sum SPECIFIC_EPITHET_FINAL
  mutate(prop = SPECIFIC_EPITHET_FINAL/sum(SPECIFIC_EPITHET_FINAL)) %>% ## mutate the df by adding prop that is each #sp/total
  complete(Nativity, fill = list(SPECIFIC_EPITHET_FINAL = 0, prop = 0)) ## keep all levels of factor and replace NA with zeros for both   SPECIFIC_EPITHET_FINAL and prop

#checkout color packages, ggplot color package
# Check it adds to one with the 5 groups  
sum(df.props_nativity_sb$prop[1:2])
    

#View(df.props_nativity_sb)

#get the means across transect (transected is nested within baseline as replication)
df_nativity_means <- df.props_nativity_sb %>%
  group_by(Baseline, Bank_Location, Nativity) %>%
  dplyr::summarise(Mean = mean(prop))
#View(df_nativity_means)

#get the means again but average bank location as well
df_nativity_means1 <- df.props_nativity_sb %>%
  group_by(Baseline, Nativity) %>%
  dplyr::summarise(Mean = mean(prop))
View(df_nativity_means1)


#Make boxplot with means

#boxplot without bank location
N <- df_nativity_means1 %>% 
  ggplot(aes(x=Nativity, y=Mean, fill=Nativity))+ 
  geom_boxplot()+
    geom_point()+
    labs(x = "Nativity", y = "Proportion of Seedbank")+
    stat_summary(fun=mean, geom="point", aes(group = Nativity), position = position_dodge(.9), shape=20, size=2.5, color="orange", fill="orange")+
    theme_bw(base_size = 10)+
    theme(legend.position = "none", axis.text.x=element_text(angle=45, hjust=1))+
    scale_fill_brewer(palette = "BuPu")
print(N)


#seperate by bank location
N <- df_nativity_means %>% 
  ggplot(aes(x=Nativity, y=Mean, fill=Nativity))+ 
  geom_boxplot()+
    geom_point()+
    labs(x = "Nativity", y = "Proportion of Seedbank")+
    stat_summary(fun=mean, geom="point", aes(group = Nativity), position = position_dodge(.9), shape=20, size=2.5, color="orange", fill="orange")+
    theme_bw(base_size = 10)+
    theme(legend.position = "none", axis.text.x=element_text(angle=45, hjust=1))+
    scale_fill_brewer(palette = "BuPu")
print(N)
N_BL <- N + facet_wrap(~Bank_Location)
print(N_BL)

#Make stacked bar graph 

Nativity_stacked <- aggregate(Mean ~ Bank_Location + Nativity , data = df_nativity_means, FUN = mean)

#View(Nativity_stacked)

St_Nativity <- Nativity_stacked %>%
  ggplot(aes(fill = Nativity, y = Mean, x = Bank_Location))+
  geom_bar(position = "stack", stat = "identity", color = "black") +
  labs(x = "Bank Location", y = "Proportion of Seed Bank") +
  theme_bw(base_size = 16) +
  scale_fill_brewer(palette = "BuPu")

print(St_Nativity)

#Violin Plot
Nativity_v <- df_nativity_means %>%  # violin plot
  ggplot(aes(x=Nativity, y=Mean, fill=Nativity))+ 
    geom_violin ()+
    theme(
      legend.position="none",
      plot.title = element_text(size=11)
    ) +
    xlab("Nativity") +
    ylab("Proportion of Seed Bank")
print(Nativity_v)

#Violin by bank location
N_BL_V <- Nativity_v + facet_wrap(~Bank_Location)
print(N_BL_V)


```

```{r radar/spider charts}

#get proportions of short-lived, long-lived, FAC,  FACU/UPL, FACW/OBL, forb and graminoid for both native and introduced --> of the native, what proportion (out of whole?) & vice versa
#will need to remove any row that doesn't have all info listed (including Juncus sp.)
seedbankdf$Nativity <- as.factor(seedbankdf$Nativity)
seedbankdf$WIS_Grouped <- as.factor(seedbankdf$WIS_Grouped)

#count of native and introduced
native_count <- seedbankdf %>% 
  drop_na(Species_Name, WIS_Grouped, Habit, Longevity_2, Nativity) %>%
  filter(Habit !="Woody") %>%
  filter(Longevity_2 !="Variable") %>%
  group_by(Nativity) %>% 
  summarise(count = n())

view(native_count)

#INTRODUCED
#WIS
introd_WIS_count <- seedbankdf %>% 
  drop_na(Species_Name, WIS_Grouped, Habit, Longevity_2, Nativity) %>%
  filter(Habit !="Woody") %>%
  filter(Longevity_2 !="Variable") %>%
  subset(Nativity == "Introduced") %>%
  group_by(WIS_Grouped) %>% 
  summarise(count = n())
  
view(introd_WIS_count)

#Longevity
introd_longevity_count <- seedbankdf %>% 
  drop_na(Species_Name, WIS_Grouped, Habit, Longevity_2, Nativity) %>%
  filter(Habit !="Woody") %>%
  filter(Longevity_2 !="Variable") %>%
  subset(Nativity == "Introduced") %>%
  group_by(Longevity_2) %>% 
  summarise(count = n())
  
view(introd_longevity_count)

#habit
introduced_habit_count <- seedbankdf %>% 
  drop_na(Species_Name, WIS_Grouped, Habit, Longevity_2, Nativity) %>%
  filter(Habit !="Woody") %>%
  filter(Longevity_2 !="Variable") %>%
  subset(Nativity == "Introduced") %>%
  group_by(Habit) %>% 
  summarise(count = n())
  
view(introduced_habit_count)

#NATIVE counts
#WIS
native_WIS_count <- seedbankdf %>% 
  drop_na(Species_Name, WIS_Grouped, Habit, Longevity_2, Nativity) %>%
  filter(Habit !="Woody") %>%
  filter(Longevity_2 !="Variable") %>%
  subset(Nativity == "Native") %>%
  group_by(WIS_Grouped) %>% 
  summarise(count = n())
  
view(native_WIS_count)

#Longevity
native_longevity_count <- seedbankdf %>% 
  drop_na(Species_Name, WIS_Grouped, Habit, Longevity_2, Nativity) %>%
  filter(Habit !="Woody") %>%
  filter(Longevity_2 !="Variable") %>%
  subset(Nativity == "Native") %>%
  group_by(Longevity_2) %>% 
  summarise(count = n())
  
view(native_longevity_count)

#Habit
native_habit_count <- seedbankdf %>% 
  drop_na(Species_Name, WIS_Grouped, Habit, Longevity_2, Nativity) %>%
  filter(Habit !="Woody") %>%
  filter(Longevity_2 !="Variable") %>%
  subset(Nativity == "Native") %>%
  group_by(Habit) %>% 
  summarise(count = n())
  
view(native_habit_count)

#build a data frame with proportions
metric <- c("Short-lived", "Long-lived", "OBL/FACW", "FAC", "UPL/FACU", "FORB", "Graminoid")
Introduced <- c(92, 172, 1, 52, 211, 193, 71)
Native <- c(79, 177, 199, 18, 39, 80, 176)

DF_Spider <- data.frame(metric, Introduced, Native)
  
#build a data frame with counts
Nativity <- c("Native", "Introduced")
Shortlived <- c(79, 92)
Longlived <- c(177, 171)
OBL_FACW <- c(199, 1)
FAC <- c(18, 52)
UPL_FACU <- c(39, 210)
Forb <- c(80, 193)
Graminoid <- c(176, 71)

DF_Spider_2 <- data.frame(Nativity, Shortlived, Longlived, OBL_FACW, FAC, UPL_FACU, Forb, Graminoid)


#pivot and calc proportions
t<-t(DF_Spider_2)
t<-as.data.frame(t)
t<-janitor::row_to_names(t,row_number=1)
t$'1'<-1
t$'2'<-0
t$Native<-as.numeric(t$Native)/256
t$Introduced<-as.numeric(t$Introduced)/263
t <- t[, c("1", "2", "Native",'Introduced')] # leave the row index blank to keep all rows
DF_Spider_2<-t(t)
DF_Spider_2<-as.data.frame(DF_Spider_2)
view(DF_Spider_2)

view(radar_df)

# plot with default options:
radarchart(DF_Spider_2)

# Set graphic colors
library(RColorBrewer)
coul <- brewer.pal(3, "Dark2")
colors_border <- coul
library(scales)
colors_in <- alpha(coul,0.3)

#customize
radarchart(DF_Spider_2, axistype=1 , 
    title = "Seed Bank",
    #custom polygon
    pcol=colors_border , pfcol=colors_in , plwd=4 , plty=1,
    #custom the grid
    cglcol="darkgrey", cglty=1, axislabcol="darkgrey", caxislabels=seq(0,1), cglwd=0.8,
    #custom labels
    vlcex=1)
#add legend
legend(x=.6, y=1.4, legend = rownames(DF_Spider_2[-c(1,2),]), bty = "n", pch=20 , col=colors_in , text.col = "darkgrey", cex=1.2, pt.cex=3)


#EXAMPLE radar
# Library
library(fmsb)

# Create data: note in High school for several students
set.seed(99)
data <- as.data.frame(matrix( sample( 0:20 , 15 , replace=F) , ncol=5))
colnames(data) <- c("math" , "english" , "biology" , "music" , "R-coding" )
rownames(data) <- paste("mister" , letters[1:3] , sep="-")

view(data)
# To use the fmsb package, I have to add 2 lines to the dataframe: the max and min of each variable to show on the plot!
data <- rbind(rep(20,5) , rep(0,5) , data)
 
# plot with default options:
radarchart(data)

#variable
# Set graphic colors
library(RColorBrewer)
coul <- brewer.pal(3, "BuPu")
colors_border <- coul
library(scales)
colors_in <- alpha(coul,0.3)

radarchart( data  , axistype=1 , 
    #custom polygon
    pcol=colors_border , pfcol=colors_in , plwd=4 , plty=1,
    #custom the grid
    cglcol="grey", cglty=1, axislabcol="grey", caxislabels=seq(0,20,5), cglwd=0.8,
    #custom labels
    vlcex=0.8 
    )

```

```{r graph rank abundance curve}

#Prepping data file for proportion as response variable

vegdf$VegHit_SoilSurfaceHit <- as.factor(vegdf$VegHit_SoilSurfaceHit)

df.props_RankAbund_veg <- vegdf %>%
  group_by(sample.bout, baseline, baseline.rep, Transect, Hit.Number, Bank_Location, Species.Hit, VegHit_SoilSurfaceHit) %>%
  filter(sample.bout =="1") %>%
  subset(VegHit_SoilSurfaceHit!="bare soil" & VegHit_SoilSurfaceHit!="downed woody debris"
         & VegHit_SoilSurfaceHit!="litter" & VegHit_SoilSurfaceHit!="rock" & VegHit_SoilSurfaceHit!="water" & VegHit_SoilSurfaceHit!="NULL") %>%
  drop_na(Species.Hit, VegHit_SoilSurfaceHit) %>%  ## drops rows with missing values NA in either Species.Hit 
  summarise(Species.Hit = n()) %>%  ## from the group_by groupings, count the number 
  group_by(baseline, Transect, Bank_Location, VegHit_SoilSurfaceHit) %>%  
  summarise(Species.Hit = sum(Species.Hit)) %>% ## groups by baseline and Bank_location to sum species.Hit
  mutate(prop = Species.Hit/sum(Species.Hit)) %>% ## mutate the df by adding prop that is each #sp/total
  complete(VegHit_SoilSurfaceHit, fill = list(Species.Hit = 0, prop = 0)) %>% ## keep all levels of factor and replace NA with zeros for both Species.Hit and prop
  subset(VegHit_SoilSurfaceHit!="bare soil" & VegHit_SoilSurfaceHit!="downed woody debris"
         & VegHit_SoilSurfaceHit!="litter" & VegHit_SoilSurfaceHit!="rock" & VegHit_SoilSurfaceHit!="water" & VegHit_SoilSurfaceHit!="NULL") #remove after complete function so they aren't included in graphs (same as with FG)

vegdf$VegHit_SoilSurfaceHit <- as.factor(vegdf$VegHit_SoilSurfaceHit)


seedbankdf$Species <- as.factor(seedbankdf$Species)
seedbankdf$Species_Name <- as.factor(seedbankdf$Species_Name)


df.props_RankAbund_seed <- seedbankdf %>%
  filter(Species_Name !="Unknown Poaceae") %>% #removing these groups from the graph (NAs were already dropped)
 filter(Species_Name !="Unknown graminoid") %>%
 filter(Species_Name !="Unknown") %>%
 filter(Species_Name !="Unknown forb") %>%
  group_by(Baseline, Transect_ID, Bank_Location, Species_Name, Species) %>%
  drop_na(Species_Name) %>%  ## drops rows with missing values NA in either SPECIFIC_EPITHET_FINAL or WIS
  summarise(Species = n()) %>%  ## from the group_by groupings, count the number 
  group_by(Baseline, Transect_ID, Bank_Location, Species_Name) %>% #added transect so I can get mean
  summarise(Species = sum(Species)) %>%  ## groups by baseline and Bank_location to sum SPECIFIC_EPITHET_FINAL
  mutate(prop = Species/sum(Species)) %>% ## mutate the df by adding prop that is each #sp/total
  complete(Species_Name, fill = list(Species = 0, prop = 0)) %>% ## keep all levels of factor and replace NA with zeros for both   SPECIFIC_EPITHET_FINAL and prop
  filter(Species_Name !="Unknown Poaceae") %>% #removing these groups from the graph (NAs were already dropped)
 filter(Species_Name !="Unknown graminoid") %>%
 filter(Species_Name !="Unknown") %>%
 filter(Species_Name !="Unknown forb")
#checkout color packages, ggplot color package



# Check it adds to one with the 5 groups  
sum(df.props_RankAbund_veg$prop[1:50])
    
View(df.props_RankAbund_seed)

#get the means across transect (transected is nested within baseline as replication)
df_RankAbund_means_seed <- df.props_RankAbund_seed %>%
  group_by(Baseline, Bank_Location, Species_Name) %>%
  dplyr::summarise(Mean = mean(prop))

View(df_RankAbund_means_seed)

#get the means again but average bank location as well
df_RankAbund_means_seed2 <- df.props_RankAbund_seed %>%
  group_by(Baseline, Species_Name) %>%
  dplyr::summarise(Mean = mean(prop))

View(df_RankAbund_means_seed2)


# means again but average across all to get most common species
df_RankAbund_means_seed3 <- df.props_RankAbund_seed %>%
  group_by(Species_Name) %>%
  dplyr::summarise(Mean = mean(prop))

View(df_RankAbund_means_seed3)

Common_seed_species <- df_RankAbund_means_seed3 %>%
  filter(Mean > 0.0199) %>%
  arrange(Mean)


View(Common_seed_species)

#boxplot without bank location (not needed)

RankAbund_seed <- df_RankAbund_means_seed2 %>%
  filter(Species_Name == "Taraxacum officinale"
         | Species_Name == "Juncus sp." 
         | Species_Name == "Phalaris arundinacea"
         | Species_Name == "Rumex crispus" 
         | Species_Name == "Rorippa palustris" 
         | Species_Name == "Bromus tectorum"
         | Species_Name == "Capsella bursa-pastoris" 
         | Species_Name == "Carex sp." 
         | Species_Name == "Plantago major"
         | Species_Name == "Carex emoryi") %>%
  mutate(Species_Name = fct_relevel(Species_Name, "Taraxacum officinale", "Juncus sp.", "Phalaris arundinacea", "Rumex crispus", "Rorippa palustris", "Bromus tectorum", "Capsella bursa-pastoris",  "Carex sp.", "Plantago major", "Carex emoryi")) %>% 
  ggplot(aes(x=factor(Species_Name), y=Mean, fill=Species_Name))+ 
  geom_boxplot()+
    geom_point()+
    labs(x = "Species", y = "Proportion of Seed Bank")+
    stat_summary(fun=mean, geom="point", aes(group = Species_Name), position = position_dodge(.9), shape=20, size=2.5, color="purple", fill="purple")+
    theme_bw(base_size = 10)+
    theme(legend.position = "none", axis.text.x=element_text(angle=45, hjust=1))+
    scale_fill_brewer(palette = "RdBu")


print(RankAbund_seed)


#all speciees RAC

RankAbund_seed2 <- df_RankAbund_means_seed2 %>%
  ggplot(aes(x=reorder(factor(Species_Name), -Mean), y=Mean))+ 
  geom_boxplot()+
    geom_point(data =df_RankAbund_means_seed3, mapping = aes (x=Species_Name, y =Mean) )+
    labs(x = "Species", y = "Proportion of Seed Bank")+
    stat_summary(fun=mean, geom="point", aes(group = Species_Name), position = position_dodge(.9), shape=20, size=2.5, color="purple", fill="purple")+
    theme_bw(base_size = 10)+
    theme(legend.position = "none", axis.text.x=element_text(angle=45, hjust=1))+
    geom_line(data=df_RankAbund_means_seed3, mapping =aes(x = Species_Name, y = Mean))


print(RankAbund_seed2)

#all species RAC// with line connecting mean

RankAbund_seed2 <- df_RankAbund_means_seed2 %>%
  ggplot(aes(x=reorder(factor(Species_Name), -Mean), y=Mean))+ #not reordered perfectly, not sure how to fix
  geom_boxplot()+
    geom_point(data =df_RankAbund_means_seed3, mapping = aes (x=Species_Name, y =Mean), color="purple") +
    geom_line(data = df_RankAbund_means_seed3, mapping = aes(x = Species_Name, y = Mean, group=1)) +
    labs(x = "Species", y = "Proportion of Seed Bank")+
    theme_bw(base_size = 10)+
    theme(legend.position = "none", axis.text.x=element_text(angle=45, hjust=1))
    


print(RankAbund_seed2)
 

```



```{r stats for WIS with WIS and bank location interaction}
#Need to run code in chunk above named "r graph WIS by bank location" that creates the data file df.props_WIS_seed
#Create competing models
#decided poisson won't work bc it is proportion. Will run in the same way as the veg data

lmer_sb_null <- lmer(prop ~ 1 + (1|Baseline) + (1|Transect_ID:Baseline), data = df.props_WIS_seed) #intercept only, just models variation across baselines and transects, no accounting for variation explained by WIS
lmer_sb1 <- lmer(prop ~ WIS + (1|Baseline) + (1|Transect_ID:Baseline), data = df.props_WIS_seed) #add in variation explained by WIS
lmer_sb2 <- lmer(prop ~ WIS + Bank_Location + (1|Baseline) + (1|Transect_ID:Baseline), data = df.props_WIS_seed) #add in variation explained by bank location
lmer_sb3 <- lmer(prop ~ WIS + Bank_Location + WIS*Bank_Location + (1|Baseline) + (1|Transect_ID:Baseline), data = df.props_WIS_seed) #add in interaction term
lmer_sb4 <- lmer(prop ~ WIS + Bank_Location + WIS*Bank_Location + (1|Baseline), data = df.props_WIS_seed) #Remove random effect of transect within baseline

AIC(lmer_sb_null, lmer_sb1,lmer_sb2,lmer_sb3, lmer_sb4) #code to run AIC; lowest number is best fit; typically considered that difference should be at least 2 to be considered a meaningful improvement of fit
#why is AIC for null best for sb WIS? --> due to AIC penalizing adding variables, we can use biological knowledge to override 

summary(lmer_sb1) #Get model output
summary(lmer_sb2) #Get model output
summary(lmer_sb3) #Get model output
summary(lmer_sb4) #Get model output

WIS_SB_model_summary<-as.data.frame(coef(summary(lmer_sb4))) #put coefficients into dataframe

#write.csv(WIS_SB_model_summary, 'WIS_SB_model_summary.csv', row.names = TRUE) #CSV, keeping names in index

#Different ways to visualize the distribution of the data; the raw data (distribution of y) is not normally distributed but the model fit
#(with y conditional on x) looks decent (although still violates normality) based on qqplot and distribution of fitted versus residuals

#Can also get the output for lines 599-603 below using sjPlot code 

proportion_WIS <- df.props_WIS_seed$prop #Histogram showing lots of zeroes, positive skew 
hist(proportion_WIS)
qqnorm(df.props_WIS_seed$prop) #use to visualize whether raw data are normally distributed
qqnorm(resid(lmer_sb4))     #Use to visualize whether model residuals vs predicted are normally distributed
plot(glmer_pois4)              #Use to visualize whether model residuals vs predicted are normally distributed


#Choose lmer_gaus_upper4 based on AIC and run diagnostics, output, pairwise comparisons (from veg code)

#effectsize::standardize(lmer_gaus_upper2) %>% summary()
#Diagnostics
plot_residuals(lmer_sb4)
plot_model(lmer_sb4, type = "diag")
sjPlot::plot_model(lmer_sb4, type = "est", show.values = T)
#explaination for the top one, these are estimates WIS FACU : -.07, meaning that facultative upland spp have 7% less cover than facultative species, across all bank locations, but that diff is not significant because no star (indicating p value)

#creates table; information from the ANOVA
sjPlot::tab_model(lmer_sb4, df.method = "satterthwaite", title = "Proportion WIS in Vegetation", dv.labels = "Proportion Cover")


#post hoc: tukey/ familywise error rate
emmeans(lmer_sb4, df.method = "satterthwaite", pairwise ~ WIS | Bank_Location, adjust = "tukey")

#export
WIS_emmeans_output_SB<-as.data.frame(emmeans(lmer_sb4, df.method = "satterthwaite", pairwise ~ WIS | Bank_Location, adjust = "tukey")) #data frame
write_xlsx(WIS_emmeans_output_SB, 'WIS_emmeans_output_SB.xlsx')

emmip(lmer_sb4, WIS ~ Bank_Location, CIs = TRUE)
emmip(lmer_sb4, WIS ~ Bank_Location)

#customizations
emmip(lmer_sb4, WIS ~ Bank_Location, CIs = TRUE, linearg = list(),
      CIarg = list(lwd = 1, alpha = 1)) +
  ggplot2::theme_bw()  +
  ylab("Linear Prediction of Seed Bank Wetland Indicator Status (WIS) Proportion") +       
  xlab("Bank Location") +
  ggtitle("Seed Bank")

emmip(lmer_sb4, WIS ~ Bank_Location, linearg = list(),
      CIarg = list(lwd = 1, alpha = 1)) +
  ggplot2::theme_bw()  +
  ylab("Linear Prediction of Seed Bank Wetland Indicator Status (WIS) Proportion") +       
  xlab("Bank Location") +
  ggtitle("Seed Bank")


  
  

```

```{r nativity stats with nativity and bank location interaction}

#Need to run code in chunk above named "r graph native/intro by bank location" that creates the data file df.props_Nativity_veg 

#Create competing models

lmer_gaus__native_null <- lmer(prop ~ 1 + (1|Baseline) + (1|Transect_ID:Baseline), data = df.props_nativity_sb) #intercept only, just models variation across baselines and transects, no accounting for variation explained by nativity
lmer_gaus_native_1 <- lmer(prop ~ Nativity + (1|Baseline) + (1|Transect_ID:Baseline), data = df.props_nativity_sb) #add in variation explained by nativity
lmer_gaus_native_2 <- lmer(prop ~ Nativity + Bank_Location + (1|Baseline) + (1|Transect_ID:Baseline), data = df.props_nativity_sb) #add in variation explained by bank location
lmer_gaus_native_3 <- lmer(prop ~ Nativity + Bank_Location + Nativity*Bank_Location + (1|Transect_ID:Baseline) + (1|Transect_ID:Baseline), data = df.props_nativity_sb) #add in interaction term
lmer_gaus_native_4 <- lmer(prop ~ Nativity + Bank_Location + Nativity*Bank_Location + (1|Transect_ID:Baseline), data = df.props_nativity_sb) #Remove random effect of transect within baseline

AIC(lmer_gaus_native_1, lmer_gaus_native_2, lmer_gaus_native_3, lmer_gaus_native_4)
#lmer_gau_native_4 has lowest AIC | variation explained by nativity, bank location, interaction; random effect of transect within baseline removed



summary(lmer_gaus_native_1)
summary(lmer_gaus_native_2)
summary(lmer_gaus_native_3)
summary(lmer_gaus_native_4) #lowest AIC

N_SB_model_summary<-as.data.frame(coef(summary(lmer_gaus_native_4))) #put coefficients into dataframe

#write.csv(N_SB_model_summary, 'N_SB_model_summary.csv', row.names = TRUE) #CSV, keeping names in index

#Different ways to visualize distribution of the raw data and model fitted data (y conditional on x)

proportion_Nativity_gauss <- df.props_nativity_sb$prop #Histogram showing lots of zeroes and ones 
hist(proportion_Nativity_gauss)
qqnorm(df.props_nativity_sb$prop) #use to visualize whether raw data are normally distributed
qqnorm(resid(lmer_gaus_native_4))     #Use to visualize whether model residuals vs predicted are normally distributed
plot(lmer_gaus_native_4)              #Use to visualize whether model residuals vs predicted are normally distributed

qqnorm(resid(lmer_gaus_native_4)) #Use to visualize whether normally distributed
plot(lmer_gaus_native_4)


#Choose lmer_gaus_native_4 based on AIC and run diagnostics, output, pairwise comparisons

#effectsize::standardize(lmer_gaus_upper2) %>% summary()
plot_residuals(lmer_gaus_native_4)
plot_model(lmer_gaus_native_4, type = "diag")
sjPlot::plot_model(lmer_gaus_native_4, type = "est", show.values = T)

sjPlot::tab_model(lmer_gaus_native_4, df.method = "satterthwaite", title = "Proportion Native and Introduced in Vegetation", dv.labels = "Proportion Cover")

emmeans(lmer_gaus_native_4, df.method = "satterthwaite", pairwise ~ Nativity | Bank_Location, adjust = "tukey")

nativ_emmeans_output_SB<-as.data.frame(emmeans(lmer_gaus_native_4, df.method = "satterthwaite", pairwise ~ Nativity | Bank_Location, adjust = "tukey")) #data frame
#write_xlsx(nativ_emmeans_output_SB, 'nativ_emmeans_output_SB.xlsx')

emmip(lmer_gaus_native_4, Nativity~ Bank_Location, CIs = TRUE)
emmip(lmer_gaus_native_4, Nativity~ Bank_Location) #without CIs

#customizations
emmip(lmer_gaus_native_4, Nativity ~ Bank_Location, CIs = TRUE, linearg = list(),
      CIarg = list(lwd = 1, alpha = 1)) +
  ggplot2::theme_bw() +
  ylab("Linear Prediction of Seed Bank Nativity Proportion") +       
  xlab("Bank Location") +
  ggtitle("Seed Bank")

#not needed for nativity (very legible)
emmip(lmer_gaus_native_4, Nativity ~ Bank_Location, linearg = list(),
      CIarg = list(lwd = 1, alpha = 1)) +
  ggplot2::theme_bw()  +
  ylab("Linear Prediction of Seed Bank Nativity Proportion") +       
  xlab("Bank Location") +
  ggtitle("Seed Bank")
```

```{r stats for functional group by bank location interaction}

#Need to run code in chunk above named "r graph functional groups by bank location" that creates the data file df.props_FG

#Create competing models
view(df.props_FunctGroup_seed)

lmer_gaus_null <- lmer(prop ~ 1 + (1|Baseline) + (1|Transect_ID:Baseline), data = df.props_FunctGroup_seed)
lmer_gaus_fg_1 <- lmer(prop ~ FunctionalGroup + (1|Baseline) + (1|Transect_ID:Baseline), data = df.props_FunctGroup_seed)
lmer_gaus_fg_2 <- lmer(prop ~ FunctionalGroup + Bank_Location + (1|Baseline) + (1|Transect_ID:Baseline), data = df.props_FunctGroup_seed)
lmer_gaus_fg_3 <- lmer(prop ~ FunctionalGroup + Bank_Location + FunctionalGroup*Bank_Location + (1|Transect_ID:Baseline) + (1|Transect_ID:Baseline), data = df.props_FunctGroup_seed)
lmer_gaus_fg_4 <- lmer(prop ~ FunctionalGroup + Bank_Location + FunctionalGroup*Bank_Location + (1|Baseline), data = df.props_FunctGroup_seed)

AIC(lmer_gaus_null, lmer_gaus_fg_1, lmer_gaus_fg_2,lmer_gaus_fg_3, lmer_gaus_fg_4)

summary(lmer_gaus_fg_1)
summary(lmer_gaus_fg_2)
summary(lmer_gaus_fg_3)
summary(lmer_gaus_fg_4) #not lowest AIC but chosen model

FG_SB_model_summary<-as.data.frame(coef(summary(lmer_gaus_fg_4))) #put coefficients into dataframe

#write.csv(FG_SB_model_summary, 'FG_SB_model_summary.csv', row.names = TRUE) #CSV, keeping names in index
#Different ways to visualize distribution of the raw data and model fitted data (y conditional on x)

proportion_fg_gauss <- df.props_FunctGroup_seed$prop #Histogram showing lots of zeroes and ones 
hist(proportion_fg_gauss)
qqnorm(df.props_FunctGroup_seed$propFG) #use to visualize whether raw data are normally distributed
qqnorm(resid(lmer_gaus_fg_4))     #Use to visualize whether model residuals vs predicted are normally distributed
plot(lmer_gaus_fg_4)              #Use to visualize whether model residuals vs predicted are normally distributed



#effectsize::standardize(lmer_gaus_upper2) %>% summary()
plot_residuals(lmer_gaus_fg_4)
plot_model(lmer_gaus_fg_4, type = "diag")
sjPlot::plot_model(lmer_gaus_fg_4, type = "est", show.values = T)

sjPlot::tab_model(lmer_gaus_fg_4, df.method = "satterthwaite", title = "Proportion of Functional Groups in Vegetation", dv.labels = "Proportion Cover")

emmeans(lmer_gaus_fg_4, df.method = "satterthwaite", pairwise ~ Functional_Group_2, adjust = "tukey")


emmeans(lmer_gaus_fg_4, df.method = "satterthwaite", pairwise ~ Functional_Group_2 | Bank_Location, adjust = "tukey")

FG_emmeans_output_SB<-as.data.frame(emmeans(lmer_gaus_fg_4, df.method = "satterthwaite", pairwise ~ Functional_Group_2 | Bank_Location, adjust = "tukey")) #data frame
write_xlsx(FG_emmeans_output_SB, 'FG_emmeans_output_SB.xlsx')


emmip(lmer_gaus_fg_4, FunctionalGroup ~ Bank_Location, CIs = TRUE)
emmip(lmer_gaus_fg_4, FunctionalGroup ~ Bank_Location)

#customizations

emmip(lmer_gaus_fg_4, FunctionalGroup ~ Bank_Location, CIs = TRUE, linearg = list(),
      CIarg = list(lwd = 1, alpha = 1)) +
  ggplot2::theme_bw()+
  ylab("Linear Prediction of Seed Bank Functional Group Proportion") +       
  xlab("Bank Location") +
  ggtitle("Seed Bank") 

  #scale_fill_discrete(name = "Functional Group") #not able to change legend title yet
  

emmip(lmer_gaus_fg_4, FunctionalGroup ~ Bank_Location, linearg = list(),
      CIarg = list(lwd = 1, alpha = 1)) +
  ggplot2::theme_bw() +
  ylab("Linear Prediction of Seed Bank Functional Group Proportion") +       
  xlab("Bank Location") +
  ggtitle("Seed Bank")

```

```{r stats for WIS with WIS and bank location interaction_WISGROUPED}

#Prepping data to compute proportions
#By baseline and bank location
seedbankdf[seedbankdf == 'Juncus sp. (FACW-OBL)'] <- 'Juncus sp.*' #Changing name so it looks nicer in graph

#view(seedbank)
seedbankdf$WIS_Grouped <- as.factor(seedbankdf$WIS_Grouped)

df.props_WIS_seed_grouped <- seedbankdf %>%
  group_by(Baseline, Transect_ID, Bank_Location, WIS_Grouped, Longevity_1, Habit, Functional_Group_1, Nativity) %>%
  drop_na(Species_Name, WIS_Grouped) %>%  ## drops rows with missing values NA in either SPECIFIC_EPITHET_FINAL or WIS
  summarise(Species_Name = n()) %>%  ## from the group_by groupings, count the number 
  group_by(Baseline, Transect_ID, Bank_Location, WIS_Grouped) %>% #added transect so I can get mean
  summarise(Species_Name = sum(Species_Name)) %>%  ## groups by baseline and Bank_location to sum SPECIFIC_EPITHET_FINAL
  mutate(prop = Species_Name/sum(Species_Name)) %>% ## mutate the df by adding prop that is each #sp/total
  complete(WIS_Grouped, fill = list(Species_Name = 0, prop = 0)) ## keep all levels of factor and replace NA with zeros for both   SPECIFIC_EPITHET_FINAL and prop
#checkout color packages, ggplot color package

view(df.props_WIS_seed_grouped)


# Check it adds to one with the 3 groups  
sum(df.props_WIS_seed_grouped$prop[1:3])
#view(df.props_WIS_seed)


#Create competing models

lmer_sb_null <- lmer(prop ~ 1 + (1|Baseline) + (1|Transect_ID:Baseline), data = df.props_WIS_seed_grouped) #intercept only, just models variation across baselines and transects, no accounting for variation explained by WIS
lmer_sb1 <- lmer(prop ~ WIS_Grouped + (1|Baseline) + (1|Transect_ID:Baseline), data = df.props_WIS_seed_grouped) #add in variation explained by WIS
lmer_sb2 <- lmer(prop ~ WIS_Grouped + Bank_Location + (1|Baseline) + (1|Transect_ID:Baseline), data = df.props_WIS_seed_grouped) #add in variation explained by bank location
lmer_sb3 <- lmer(prop ~ WIS_Grouped + Bank_Location + WIS_Grouped*Bank_Location + (1|Baseline) + (1|Transect_ID:Baseline), data = df.props_WIS_seed_grouped) #add in interaction term
lmer_sb4 <- lmer(prop ~ WIS_Grouped + Bank_Location + WIS_Grouped*Bank_Location + (1|Baseline), data = df.props_WIS_seed_grouped) #Remove random effect of transect within baseline

AIC(lmer_sb_null, lmer_sb1,lmer_sb2,lmer_sb3, lmer_sb4) #code to run AIC; lowest number is best fit; typically considered that difference should be at least 2 to be considered a meaningful improvement of fit
#why is AIC for null best for sb WIS? --> due to AIC penalizing adding variables, we can use biological knowledge to override 

summary(lmer_sb1) #Get model output
summary(lmer_sb2) #Get model output
summary(lmer_sb3) #Get model output
summary(lmer_sb4) #Get model output

WISG_SB_model_summary<-as.data.frame(coef(summary(lmer_sb4))) #put coefficients into dataframe

write.csv(WISG_SB_model_summary, 'WIS_G_SB_model_summary.csv', row.names = TRUE) #CSV, keeping names in index

#Different ways to visualize distribution of the raw data and model fitted data (y conditional on x)

#Different ways to visualize the distribution of the data; the raw data (distribution of y) is not normally distributed but the model fit
#(with y conditional on x) looks decent (although still violates normality) based on qqplot and distribution of fitted versus residuals

#Can also get the output for lines 599-603 below using sjPlot code 

proportion_WIS <- df.props_WIS_seed_grouped$prop #Histogram showing lots of zeroes, positive skew 
hist(proportion_WIS)
qqnorm(df.props_WIS_seed_grouped$prop) #use to visualize whether raw data are normally distributed
qqnorm(resid(lmer_sb4))     #Use to visualize whether model residuals vs predicted are normally distributed
plot(lmer_sb4)              #Use to visualize whether model residuals vs predicted are normally distributed


#Choose lmer_gaus_upper4 based on AIC and run diagnostics, output, pairwise comparisons (from veg code)

#effectsize::standardize(lmer_gaus_upper2) %>% summary()
#Diagnostics
plot_residuals(lmer_sb4)
plot_model(lmer_sb4, type = "diag")
sjPlot::plot_model(lmer_sb4, type = "est", show.values = T)
#explaination for the top one, these are estimates WIS FACU : -.07, meaning that facultative upland spp have 7% less cover than facultative species, across all bank locations, but that diff is not significant because no star (indicating p value)

#creates table; information from the ANOVA
sjPlot::tab_model(lmer_sb4, df.method = "satterthwaite", title = "Proportion WIS in Vegetation", dv.labels = "Proportion Cover")


#post hoc: tukey/ familywise error rate
emmeans(lmer_sb4, df.method = "satterthwaite", pairwise ~ WIS | Bank_Location, adjust = "tukey")

#export
WIS_emmeans_output_SB<-as.data.frame(emmeans(lmer_sb4, df.method = "satterthwaite", pairwise ~ WIS_Grouped | Bank_Location, adjust = "tukey")) #data frame
write_xlsx(WIS_emmeans_output_SB, 'WIS_emmeans_output_SB.xlsx')

emmip(lmer_sb4, WIS_Grouped ~ Bank_Location, CIs = TRUE)
emmip(lmer_sb4, WIS_Grouped ~ Bank_Location)

```





```{spp presence, abundance, and proportion table}

#Counted species and then calculated proportion in new column


Spp_tbl <- df_Spp %>%
  select(Species_Name, Longevity_1, Habit, Nativity, WIS) #"Spp_tbl lists 53 species and their traits

SB_Spp_count_tbl <- seedbankdf %>% 
  group_by(Species_Name, Longevity_1, Habit, WIS, Nativity) %>%
  summarise(Freq2 = n())

view(SB_Spp_count_tbl)

Spp_prop_tbl <- Spp_count_tbl %>% 
  mutate(prop = Freq2/sum(Spp_count_tbl$Freq2))

view(Spp_prop_tbl)
sum(Spp_count_tbl$Freq2)
#write_xlsx(Spp_prop_tbl, 'Veg_SppList_Prop3_AI08052022.xlsx')



```

```{r count hits (VEG) at each level of organization: canal, baseline, transect}

#Summing number of hits at each level of organization (whole canal, baselines, transects)

#Whole-canal level: number of species hits by sample bout and hit number, includes foliar and ground first hits
df.sb <- seedbankdf %>% 
  group_by(Bank_Location) %>%
  summarise(Species_Name = n()) 

View(df.canal)
write_xlsx(df.canal, 'hits_byCanal.xlsx')

#Baseline level: number of species hits by sample bout and hit number, includes foliar and ground first hits
df.baseline <- vegdf %>% 
  group_by(sample.bout, baseline, Hit.Number) %>%
  summarise(Species.Hit = n()) 

View(df.baseline)

write_xlsx(df.baseline, 'hits_byBaseline.xlsx')

#Transect level: number of species hits by sample bout and hit number, includes foliar and ground first hits

df.transect <- vegdf %>% 
  group_by(sample.bout, baseline, baseline.rep, Hit.Number) %>%
  summarise(Species.Hit = n()) 

View(df.transect)

write_xlsx(df.transect, 'hits_byTransect.xlsx')

```

```{r determine common species, cutoff point 1% cover}

#Foliar hits only
#Group species counts by sample bout, hit number, transect, etc.
#Use summarise to count hits by species, drop NA's

veg_only_transect <- vegdf %>%
  group_by(sample.bout, Hit.Number, baseline, Transect, Num_transect_points, Bank_Location, FunctionalGroup, Nativity, Cvalue, WIS, Species.Hit) %>%
  summarise(Species = n()) %>%
  drop_na()

head(veg_only_transect)
View(veg_only_transect)

#The Excel file exported below has both sample bouts and hit numbers one and two

write_xlsx(veg_only_transect, 'Species_counts.xlsx')

#Foliar hits only
#summarize species proportions at scale of whole canal, includes all sample bouts and hits
#Used sum(prop_species$Freq) code to count 1909 total hits across whole canal
#Use to determine which species have at least 1% cover
#To see all species, remove the filter statement

prop_species_canal <- veg_only_transect %>%
  group_by(Species.Hit) %>%
  summarise(Freq = sum(Species)) %>%
  mutate(prop = Freq/1642) %>%
  filter(prop > 0.0099) %>%
  arrange(desc(prop))
  
View(prop_species_canal)

sum(prop_species_canal$Freq)

#Now filter out species with 1% as determine with the code above

Common_species_canal_BothBouts <- veg_only_transect %>%
  group_by(baseline) %>%
  filter(Species.Hit == "Bromus inermis"| Species.Hit == "Phalaris arundinacea" | Species.Hit == "Elymus repens"
         | Species.Hit == "Convolvulus arvensis" | Species.Hit == "Cirsium arvense" | Species.Hit == "Dactylis glomerata"
         | Species.Hit == "	Carex emoryi" | Species.Hit == "Rhamnus cathartica" | Species.Hit == "Symphyotrichum lanceolatum ssp. hesperium"
         | Species.Hit == "Taraxacum officinale" | Species.Hit == "Schedonorus arundinaceus" | Species.Hit == "Symphoricarpos occidentalis"
         | Species.Hit == "Salix exigua ssp. exigua" | Species.Hit == "Medicago sativa" | Species.Hit == "Typha angustifolia"
         | Species.Hit == "Ulmus pumila" | Species.Hit == "Bromus tectorum" | Species.Hit == "Prunus virginiana") 
  
  
View(Common_species_canal_BothBouts)

#The Excel file exported below has both sample bouts

write_xlsx(Common_species_canal_BothBouts, 'Common_species_BothBouts.xlsx')


#Same as above but look at only first sample bout 

veg_only_transect_FirstBout <- filter(veg_only_transect, sample.bout == "1")
View(veg_only_transect_FirstBout)


prop_species_canal_FirstBout <- veg_only_transect_FirstBout %>%
  group_by(Species.Hit) %>%
  summarise(Freq = sum(Species)) %>%
  mutate(prop = Freq/713) %>%
  filter(prop > 0.0099) %>%
  arrange(desc(prop))

View(prop_species_canal_FirstBout)

sum(prop_species_canal_FirstBout$Freq)

Common_species_canal_FirstBout <- veg_only_transect_FirstBout %>%
  group_by(baseline) %>%
  filter(Species.Hit == "Bromus inermis"| Species.Hit == "Phalaris arundinacea" | Species.Hit == "Elymus repens"
         | Species.Hit == "Cirsium arvense" | Species.Hit == "Convolvulus arvensis" | Species.Hit == "Taraxacum officinale" 
         | Species.Hit == "Dactylis glomerata" |Species.Hit == "Rhamnus cathartica" | Species.Hit == "Symphyotrichum lanceolatum ssp. hesperium"
         |Species.Hit == "Carex emoryi" | Species.Hit == "Bromus tectorum" | Species.Hit == "Schedonorus arundinaceus" 
         | Species.Hit == "Symphoricarpos occidentalis" | Species.Hit == "Medicago sativa" | Species.Hit == "Rumex crispus" | Species.Hit == "Prunus virginiana") 
  
  
View(Common_species_canal_FirstBout)

#The Excel file exported below has only first sample bout

write_xlsx(Common_species_canal_FirstBout, 'Common_species_FirstBout.xlsx')


#Same as above but look at only second sample bout 

veg_only_transect_secondOnly <- filter(veg_only_transect, sample.bout == "2")
View(veg_only_transect_secondOnly)


prop_species_canal_secondOnly <- veg_only_transect_secondOnly %>%
  group_by(Species.Hit) %>%
  summarise(Freq = sum(Species)) %>%
  mutate(prop = Freq/964) %>%
  filter(prop > 0.0099) %>%
  arrange(desc(prop))

View(prop_species_canal_secondOnly)

sum(prop_species_canal_secondOnly$Freq)


#Foliar hits only
#Use most common species determined above and group by bank location and baseline, includes all sample bouts and hits

prop_bank <- veg_only_transect %>%
  group_by(Species.Hit, Bank_Location) %>%
  summarise(Freq = sum(Species))

View(prop_bank)

sum(prop_bank$Freq)

#Foliar hits only
#Use the code below to create a data set where we have a list
#of each species that occurs in the upper/middle/lower banks
#Then can look at the proportion of native and intro species present that are 
#grouped into the various functional/WIS groups #Thinking we will find
#that native/intro differently distributed across the bank gradient and
#native/intro do different "jobs" based on their functional group and WIS
#Maybe use a percentage bar chart to show groups of native/intro
#by upper middle lower banks

#REDO BELOW AFTER FIRST SELECTING FOR ONLY THE FIRST SAMPLE BOUT AND FIRST HIT

prop_species_bank <- veg_only_transect %>%
  group_by(Species.Hit, Bank_Location, FunctionalGroup, Nativity, WIS) %>%
  summarise(Freq = sum(Species))

View(prop_species_bank)

#Distinct species presence by bank location

distinct_species_bank <- prop_species_bank %>%
  distinct(Bank_Location, FunctionalGroup, Nativity, WIS)%>%
  arrange(desc(Bank_Location))

View(distinct_species_bank)

```

```{r visualize unknowns}

# take "seedbankdf" and select for unknowns and "sp."

seedbank_unknowns_df <- seedbankdf %>%
  arrange(Species_Name) %>%
  subset(Species_Name=="Unknown" | Species_Name=="Unknown forb" | Species_Name=="Unknown graminoid" | Species_Name=="Unknown grass" | Species=="sp.") %>%
  select(Transect_ID, Baseline, Bank_Location, Species_Name, Species)
  
view(seedbank_unknowns_df)

#ABUNDANCES
SB_total_unknowns <- seedbank_unknowns_df %>% 
  group_by(Species_Name, Species, Baseline, Transect_ID, Bank_Location) %>%
  summarise(Freq_unk = n()) #abundances of each tray/sample (all 81)
view(SB_total_unknowns)

write_xlsx(SB_total_unknowns,'Unknowns_SB.xlsx')

SB_BL_mean_unk <- SB_total_unknowns %>%
  group_by(Species_Name, Baseline, Bank_Location) %>%
  summarise(mean_unk = mean(Freq_unk)) #averages transects to give means for baseline and bank location (27)
view(SB_BL_mean_unk)

#visualize box
Unknowns_sp_bp <- SB_BL_mean_unk %>% #box plot
  ggplot(aes(x=Bank_Location, y=mean_unk, fill=Bank_Location))+ 
  geom_boxplot()+
    geom_point()+
    labs(x = "Bank Location", y = "Mean Abundance of Unidentified Germinants")+
    stat_summary(fun=mean, geom="point", position = position_dodge(.9), shape=20, size=2.5, color="orange", fill="orange")+
    theme_bw(base_size = 10)+
    theme(legend.position = "none", axis.text.x=element_text(angle=45, hjust=1))+
    scale_fill_brewer(palette = "BuPu")
print(Unknowns_sp_bp)

#visualize violin
Unknowns_sp_bp_V <- SB_BL_mean_unk %>%  # violin plot
  ggplot(aes(x=Bank_Location, y=mean_unk, fill=Bank_Location))+ 
    geom_violin ()+
    theme(
      legend.position="none",
      plot.title = element_text(size=11)
    ) +
    xlab("Bank Location") +
    ylab("Mean Abundance of Unidentified Germinants")
print(Unknowns_sp_bp_V)


``` 

```{r visualize abundances} 
# looking at abundance of germinants in seed bank

SB_spp_abundances <- seedbankdf %>% 
  group_by(Species_Name, Longevity_1, Habit, WIS, Nativity) %>%
  summarise(Freq = n()) #shows abundances of each species

SB_total_abundances <- seedbankdf %>% 
  group_by(Baseline, Transect_ID, Bank_Location) %>%
  summarise(Freq2 = n()) #abundances of each tray/sample (all 81)

SB_BL_mean_abundance <- SB_total_abundances %>%
  group_by(Baseline, Bank_Location) %>%
  summarise(mean = mean(Freq2)) #averages transects to give means for baseline and bank location (27)
view(SB_BL_mean_abundance)

#abundance by bank location
Abundance <- SB_BL_mean_abundance %>% #box plot
  ggplot(aes(x=Bank_Location, y=mean, fill=Bank_Location))+ 
  geom_boxplot()+
    geom_point()+
    labs(x = "Bank Location", y = "Mean Abundance")+
    stat_summary(fun=mean, geom="point", position = position_dodge(.9), shape=20, size=2.5, color="orange", fill="orange")+
    theme_bw(base_size = 10)+
    theme(legend.position = "none", axis.text.x=element_text(angle=45, hjust=1))+
    scale_fill_brewer(palette = "BuPu")
print(Abundance)

Abundance_v <- SB_BL_mean_abundance %>%  # violin plot
  ggplot(aes(x=Bank_Location, y=mean, fill=Bank_Location))+ 
    geom_violin ()+
    stat_summary(fun=mean, geom="point", position = position_dodge(.9), shape=20, size=2.5, color="black", fill="black")+
    theme_bw(base_size = 10)+
  theme(
      legend.position="none",
      plot.title = element_text(size=11)
    ) +
    xlab("Bank Location") +
    ylab("Mean Abundance of Seed Bank Germinants") 
print(Abundance_v)

#abundance by baseline

SB_baseline_mean_abundance <- SB_total_abundances %>%
  group_by(Baseline, Transect_ID) %>%
  summarise(mean1 = mean(Freq2)) #averages transects to give means for baseline and bank location


Abundance_baseline <- SB_baseline_mean_abundance %>% #box plot
  mutate(Baseline = fct_relevel(Baseline, "B3", "B5", "B7", "B10", "B13", "B14", "B15", "B17", "B18")) %>%
  ggplot(aes(x=Baseline, y=mean1, fill=Baseline))+ 
  geom_boxplot()+
    geom_point()+
    labs(x = "Baseline", y = "Mean Abundance")+
    stat_summary(fun=mean, geom="point", position = position_dodge(.9), shape=20, size=2.5, color="orange", fill="orange")+
    theme_bw(base_size = 10)+
    theme(legend.position = "none", axis.text.x=element_text(angle=45, hjust=1))+
    scale_fill_brewer(palette = "BuPu")
print(Abundance_baseline)

Abundance_baseline_v <- SB_baseline_mean_abundance %>%  # violin plot
  ggplot(aes(x=Baseline, y=mean1, fill=Baseline))+ 
    geom_violin ()+
    theme(
      legend.position="none",
      plot.title = element_text(size=11)
    ) +
    xlab("Baseline") +
    ylab("Mean Abundance")
print(Abundance_baseline_v)

```

