<<<<<<< HEAD
---
title: "HLC_Veg_Analysis"
author: "Christina Alba"
date: "1/14/2022"
output: html_document
---

```{r libraries, bring in file, some data cleaning}

library(knitr); library(multcomp); library(dplyr);library(lme4);library(ggplot2); library(tidyverse); library(tidytext);
library(ggpubr); library(rstatix);library(writexl);library(ggformula); library(tidyr);library(reshape2); library(sjPlot); library(emmeans)
library(lmerTest)


#Bring in raw data file
#veg <- read.csv("Q:/Research/Grants and Funding/HighLineCanalConservancy_2019/7_Project/Stormwater_MovedToQ_UseMe/Data_Analysis/vegetation/Raw Data from RickL/20201204_allHitsData_postQC_prep4.csv")

veg <- read.csv("20201204_allHitsData_postQC_5.csv") #mac


head(veg)
str(veg)

#View(veg)

veg <- veg %>%
  mutate(sample.bout = as.factor(sample.bout))%>%
  mutate(Transect = as.factor(Transect)) %>%
  mutate(baseline = as.factor(baseline)) %>%
  mutate(baseline.rep = as.factor(baseline.rep))

#add "sp." to species names
#$ after name makes it specific so that it isn't correcting to 'Carex sp. emoryi', for example
veg_sp <- data.frame(veg)

veg$VegHit_SoilSurfaceHit<-veg_sp$VegHit_SoilSurfaceHit %>% 
  str_replace_all(c('Carex$'='Carex sp.','Persicaria$'='Persicaria sp.','Rosa$'='Rosa sp.','Sagittaria$'='Sagittaria sp.', 'Bidens$'='Bidens sp.', 'Tilia$'='Tilia sp.', 'Asclepias$'='Asclepias sp.', 'Chenopodium$'='Chenopodium sp.', 'Poa$'='Poa sp.'))

veg$Species.Hit <-veg_sp$Species.Hit %>% 
  str_replace_all(c('Carex$'='Carex sp.','Persicaria$'='Persicaria sp.','Rosa$'='Rosa sp.','Sagittaria$'='Sagittaria sp.','Bidens$'='Bidens sp.', 'Tilia$'='Tilia sp.', 'Asclepias$'='Asclepias sp.', 'Chenopodium$'='Chenopodium sp.', 'Poa$'='Poa sp.'))

#change sample bout to a factor

veg <- veg %>%
  mutate(sample.bout = as.factor(sample.bout))%>%
  mutate(baseline.rep = as.factor(baseline.rep))

str(veg)

## Remove zero from Hit.Number

veg <- veg[veg$Hit.Number != "0",]
#View(veg)

#Rename unwieldly columns; remove unwanted columns
vegdf <- veg %>% select(-Number.of.Points.Along.Transect_fromRick) %>%
rename(Num_transect_points = Number.of.points.along.transect_ChrissyCalc)

head(vegdf)
#View(vegdf)


#check species spellings

df <- vegdf %>% distinct(VegHit_SoilSurfaceHit)
#View(df)


df_Spp_v <- distinct(vegdf, Species.Hit, .keep_all = TRUE) %>%
  arrange(Species.Hit)

#view(df_Spp_v)
```



```{r create species tables for thesis}


#Pull out species names using "distinct"; arrange alphabetically using "arrange";remove 
#unwanted entries (rock, soil, litter) using "subset"; keep desired columns using "select"
#8/4 also removed bank location and functional group

vegdf_bout1 <- subset(vegdf,sample.bout =="1")
#View(df_bout1)

df_Spp_bout1 <- distinct(vegdf_bout1, VegHit_SoilSurfaceHit, .keep_all = TRUE) %>%
  arrange(VegHit_SoilSurfaceHit)%>%
  subset(VegHit_SoilSurfaceHit!="bare soil" & VegHit_SoilSurfaceHit!="downed woody debris"
         & VegHit_SoilSurfaceHit!="litter" & VegHit_SoilSurfaceHit!="rock" & VegHit_SoilSurfaceHit!="water" & VegHit_SoilSurfaceHit!="NULL")%>%
  select(VegHit_SoilSurfaceHit, Longevity, Habit, WIS_GP, Nativity) #spp richness = 58
  
view(df_Spp_bout1) #count on left skips numbers so don't use for spp count

#Export to Excel
#write_xlsx(df_Spp_bout1, 'AG_SpeciesList.xlsx') 

#Counted species and then calculated proportion in new column

Spp_count_tbl <- vegdf_bout1 %>% 
  group_by(VegHit_SoilSurfaceHit, Longevity, Habit, WIS_GP, Nativity) %>%
  summarise(Freq2 = n()) %>%
  subset(VegHit_SoilSurfaceHit!="bare soil" & VegHit_SoilSurfaceHit!="downed woody debris"
         & VegHit_SoilSurfaceHit!="litter" & VegHit_SoilSurfaceHit!="rock" & VegHit_SoilSurfaceHit!="water" & VegHit_SoilSurfaceHit!="NULL")


Spp_prop_tbl <- Spp_count_tbl %>% 
  mutate(prop = Freq2/sum(Spp_count_tbl$Freq2))

view(Spp_prop_tbl)
sum(Spp_count_tbl$Freq2) #doubled checked proportions--they are correct
#write_xlsx(Spp_prop_tbl, 'AG_SppList_proportions_2023.xlsx')

#Proportion for LOWER bank
Spp_count_tbl_Lower <- vegdf_bout1 %>% 
  filter(Bank_Location == "lower")  %>% 
  group_by(VegHit_SoilSurfaceHit, Longevity, Habit, WIS_GP, Nativity) %>%
  summarise(Freq2 = n()) %>%
  subset(VegHit_SoilSurfaceHit!="bare soil" & VegHit_SoilSurfaceHit!="downed woody debris"
         & VegHit_SoilSurfaceHit!="litter" & VegHit_SoilSurfaceHit!="rock" & VegHit_SoilSurfaceHit!="water" & VegHit_SoilSurfaceHit!="NULL")


Spp_count_tbl_Lower<- Spp_count_tbl_Lower %>% 
  mutate(prop = Freq2/sum(Spp_count_tbl_Lower$Freq2))

view(Spp_count_tbl_Lower)
sum(Spp_count_tbl$Freq2) 
write_xlsx(Spp_count_tbl_Lower, 'AG_SppList_proportions_Lower.xlsx')

#Proportion for MIDDLE bank
Spp_count_tbl_middle <- vegdf_bout1 %>% 
  filter(Bank_Location == "middle")  %>% 
  group_by(VegHit_SoilSurfaceHit, Longevity, Habit, WIS_GP, Nativity) %>%
  summarise(Freq2 = n()) %>%
  subset(VegHit_SoilSurfaceHit!="bare soil" & VegHit_SoilSurfaceHit!="downed woody debris"
         & VegHit_SoilSurfaceHit!="litter" & VegHit_SoilSurfaceHit!="rock" & VegHit_SoilSurfaceHit!="water" & VegHit_SoilSurfaceHit!="NULL")


Spp_count_tbl_middle<- Spp_count_tbl_middle %>% 
  mutate(prop = Freq2/sum(Spp_count_tbl_middle$Freq2))

view(Spp_count_tbl_middle)
sum(Spp_count_tbl_middle$Freq2) 
write_xlsx(Spp_count_tbl_middle, 'AG_SppList_proportions_Middle.xlsx')

#Proportion for Upper bank
Spp_count_tbl_upper <- vegdf_bout1 %>% 
  filter(Bank_Location == "upper")  %>% 
  group_by(VegHit_SoilSurfaceHit, Longevity, Habit, WIS_GP, Nativity) %>%
  summarise(Freq2 = n()) %>%
  subset(VegHit_SoilSurfaceHit!="bare soil" & VegHit_SoilSurfaceHit!="downed woody debris"
         & VegHit_SoilSurfaceHit!="litter" & VegHit_SoilSurfaceHit!="rock" & VegHit_SoilSurfaceHit!="water" & VegHit_SoilSurfaceHit!="NULL")


Spp_count_tbl_upper<- Spp_count_tbl_upper %>% 
  mutate(prop = Freq2/sum(Spp_count_tbl_upper$Freq2))

view(Spp_count_tbl_upper)
sum(Spp_count_tbl_upper$Freq2) 
write_xlsx(Spp_count_tbl_upper, 'AG_SppList_proportions_Upper.xlsx')

```

```{r count hits at each level of organization: canal, baseline, transect; counting veg families}

#Summing number of hits at each level of organization (whole canal, baselines, transects)

#Whole-canal level: number of species hits by sample bout and hit number, includes foliar and ground first hits
df.canal <- vegdf_bout1 %>% 
  group_by(sample.bout, Hit.Number) %>%
  summarise(Species.Hit = n()) 

View(df.canal)
#write_xlsx(df.canal, 'hits_byCanal.xlsx')

#Baseline level: number of species hits by sample bout and hit number, includes foliar and ground first hits
df.baseline <- vegdf_bout1 %>% 
  group_by(sample.bout, baseline, Hit.Number) %>%
  summarise(Species.Hit = n()) 

View(df.baseline)

write_xlsx(df.baseline, 'hits_byBaseline.xlsx')

#Transect level: number of species hits by sample bout and hit number, includes foliar and ground first hits

df.transect <- vegdf_bout1 %>% 
  group_by(sample.bout, baseline, baseline.rep, Hit.Number) %>%
  summarise(Species.Hit = n()) 

View(df.transect)

#write_xlsx(df.transect, 'hits_byTransect.xlsx')

VEG_families <- vegdf_bout1 %>% 
  group_by(Family) %>%
  summarise(Species.Name = n()) 

view(VEG_families)

write_xlsx(VEG_families, 'VEG_fam_counts_2023.xlsx')


```

```{r determine common species, cutoff point 1% cover}

#Foliar hits only
#Group species counts by sample bout, hit number, transect, etc.
#Use summarise to count hits by species, drop NA's

veg_only_transect <- vegdf %>%
  group_by(sample.bout, Hit.Number, baseline, Transect, Num_transect_points, Bank_Location, FunctionalGroup, Nativity, Cvalue, WIS_GP, Species.Hit) %>%
  summarise(Species = n()) %>%
  drop_na()

head(veg_only_transect)
View(veg_only_transect)

#The Excel file exported below has both sample bouts and hit numbers one and two

#write_xlsx(veg_only_transect, 'Species_counts.xlsx')

#Foliar hits only
#summarize species proportions at scale of whole canal, includes all sample bouts and hits
#Used sum(prop_species$Freq) code to count 1909 total hits across whole canal
#Use to determine which species have at least 1% cover
#To see all species, remove the filter statement

prop_species_canal <- veg_only_transect %>%
  group_by(Species.Hit) %>%
  summarise(Freq = sum(Species)) %>%
  mutate(prop = Freq/1642) %>%
  filter(prop > 0.0099) %>%
  arrange(desc(prop))
  
View(prop_species_canal)

sum(prop_species_canal$Freq)

#Now filter out species with 1% as determine with the code above

Common_species_canal_BothBouts <- veg_only_transect %>%
  group_by(baseline) %>%
  filter(Species.Hit == "Bromus inermis"| Species.Hit == "Phalaris arundinacea" | Species.Hit == "Elymus repens"
         | Species.Hit == "Convolvulus arvensis" | Species.Hit == "Cirsium arvense" | Species.Hit == "Dactylis glomerata"
         | Species.Hit == "	Carex emoryi" | Species.Hit == "Rhamnus cathartica" | Species.Hit == "Symphyotrichum lanceolatum ssp. hesperium"
         | Species.Hit == "Taraxacum officinale" | Species.Hit == "Schedonorus arundinaceus" | Species.Hit == "Symphoricarpos occidentalis"
         | Species.Hit == "Salix exigua ssp. exigua" | Species.Hit == "Medicago sativa" | Species.Hit == "Typha angustifolia"
         | Species.Hit == "Ulmus pumila" | Species.Hit == "Bromus tectorum" | Species.Hit == "Prunus virginiana") 
  
  
View(Common_species_canal_BothBouts)

#The Excel file exported below has both sample bouts

write_xlsx(Common_species_canal_BothBouts, 'Common_species_BothBouts.xlsx')


#Same as above but look at only first sample bout 

veg_only_transect_FirstBout <- filter(veg_only_transect, sample.bout == "1")
View(veg_only_transect_FirstBout)

#FIRST BOUT ONLY
prop_species_canal_FirstBout <- veg_only_transect_FirstBout %>%
  group_by(Species.Hit) %>%
  summarise(Freq = sum(Species)) %>%
  mutate(prop = Freq/(838)) %>% #changed to 838 based on frequency count
  filter(prop > 0.0099) %>%
  arrange(desc(prop))

View(prop_species_canal_FirstBout)

sum(prop_species_canal_FirstBout$Freq)

Common_species_canal_FirstBout <- veg_only_transect_FirstBout %>%
  group_by(baseline) %>%
  filter(Species.Hit == "Bromus inermis"| Species.Hit == "Phalaris arundinacea" | Species.Hit == "Elymus repens"
         | Species.Hit == "Cirsium arvense" | Species.Hit == "Convolvulus arvensis" | Species.Hit == "Taraxacum officinale" 
         | Species.Hit == "Dactylis glomerata" |Species.Hit == "Rhamnus cathartica" | Species.Hit == "Symphyotrichum lanceolatum ssp. hesperium"
         |Species.Hit == "Carex emoryi" | Species.Hit == "Bromus tectorum" | Species.Hit == "Schedonorus arundinaceus" 
         | Species.Hit == "Symphoricarpos occidentalis" | Species.Hit == "Medicago sativa" | Species.Hit == "Rumex crispus" | Species.Hit == "Prunus virginiana") 
  
  
View(Common_species_canal_FirstBout)

#The Excel file exported below has only first sample bout

write_xlsx(Common_species_canal_FirstBout, 'Common_species_FirstBout.xlsx')


#Same as above but look at only second sample bout 

veg_only_transect_secondOnly <- filter(veg_only_transect, sample.bout == "2")
View(veg_only_transect_secondOnly)


prop_species_canal_secondOnly <- veg_only_transect_secondOnly %>%
  group_by(Species.Hit) %>%
  summarise(Freq = sum(Species)) %>%
  mutate(prop = Freq/964) %>%
  filter(prop > 0.0099) %>%
  arrange(desc(prop))

View(prop_species_canal_secondOnly)

sum(prop_species_canal_secondOnly$Freq)


#Foliar hits only
#Use most common species determined above and group by bank location and baseline, includes all sample bouts and hits

prop_bank <- veg_only_transect %>%
  group_by(Species.Hit, Bank_Location) %>%
  summarise(Freq = sum(Species))

View(prop_bank)

sum(prop_bank$Freq)

#Foliar hits only
#Use the code below to create a data set where we have a list
#of each species that occurs in the upper/middle/lower banks
#Then can look at the proportion of native and intro species present that are 
#grouped into the various functional/WIS groups #Thinking we will find
#that native/intro differently distributed across the bank gradient and
#native/intro do different "jobs" based on their functional group and WIS
#Maybe use a percentage bar chart to show groups of native/intro
#by upper middle lower banks

#REDO BELOW AFTER FIRST SELECTING FOR ONLY THE FIRST SAMPLE BOUT AND FIRST HIT

prop_species_bank <- veg_only_transect %>%
  group_by(Species.Hit, Bank_Location, FunctionalGroup, Nativity, WIS) %>%
  summarise(Freq = sum(Species))

View(prop_species_bank)

#Distinct species presence by bank location

distinct_species_bank <- prop_species_bank %>%
  distinct(Bank_Location, FunctionalGroup, Nativity, WIS)%>%
  arrange(desc(Bank_Location))

View(distinct_species_bank)

```

```{r hit type by bare soil, litter, vegetation, water, dwd}

#Create general categories based on whether vegetation was hit first, or pin dropped straight to bare ground, litter, water
# To do this, if surface hit is NA, then hit type is vegetation, otherwise bare soil, litter, dwd, water as designated in the column

vegdf$Surface.Hit <- as.character(vegdf$Surface.Hit)

hit_type <- vegdf %>%
  group_by(sample.bout, Hit.Number, Bank_Location, baseline, Transect, Num_transect_points, Surface.Hit) %>%
  filter(sample.bout =="1") %>%
    mutate(Surface.Hit=recode(Surface.Hit, "NULL" = "Vegetation", "litter" = "Litter", 
                             "bare soil" = "Bare Soil", "water" = "Water", "downed woody debris" = "Woody Debris")) 

n_distinct(hit_type$Surface.Hit) # check number of hit types (veg, litter, bare soil, dwd, water)

View(hit_type)

#Prepping data file for proportion as response variable
#This final data set is grouped by transects

hit_type$Surface.Hit <- as.factor(hit_type$Surface.Hit)

df.prop_hit_type <- hit_type %>%
  group_by(Hit.Number, Bank_Location, baseline, Transect, Surface.Hit) %>%
  summarise(Count = n()) %>%
  mutate(prop_cover_type = Count/sum(Count)) %>%
  complete(Surface.Hit, fill = list(Count = 0, prop_cover_type = 0)) ## keep all levels of factor and replace NA with zeros for both Count and prop_cover_type

sum(df.prop_hit_type$prop_cover_type[1:5]) 

View(df.prop_hit_type)


#Make boxplot

p <- df.prop_hit_type %>% ggplot(aes(x=Surface.Hit, y=prop_cover_type))+ 
  geom_boxplot()+
  geom_point()+
  labs(x = "Cover Type", y = "Proportion of Cover")+
  stat_summary(fun=mean, geom="point", aes(group = Surface.Hit), position = position_dodge(.9), shape=20, size=2.5, color="red", fill="red")+
  theme_bw(base_size = 16)+
  theme(axis.text.x=element_text(angle=90, hjust=1))
print(p)

p + facet_wrap(~Bank_Location)



#Need to get the means of each baseline
#The above code currently graphs all 45 transects

df_prop_hit_type_means <- df.prop_hit_type %>%
  group_by(baseline, Bank_Location, Surface.Hit) %>%
  dplyr::summarise(Mean = mean(prop_cover_type))

View(df_prop_hit_type_means)

#Now create new boxplot with baseline means

COVER_TYPE <- df_prop_hit_type_means %>% 
  ggplot(aes(x=factor(Surface.Hit, levels = c('Litter', 'Vegetation', 'Bare soil', 'Woody Debris', 'Water')), y=Mean, fill=Surface.Hit))+
  geom_boxplot()+
  geom_point()+
  labs(x = "Cover Type", y = "Proportion of Cover")+
  stat_summary(fun=mean, geom="point", aes(group = Surface.Hit), position = position_dodge(.9), shape=20, size=2.5, color="yellow", fill="yellow")+
  theme_bw(base_size = 13)+
  theme(legend.position = "none", axis.text.x=element_text(angle=45, hjust=1))+
  scale_fill_brewer(palette = "Set2")
  
print(COVER_TYPE)

COVER_TYPE + facet_wrap(~Bank_Location)

COVER_TYPE_BP2 + facet_wrap(~Bank_Location)

#Make stacked bar graph 

df_stacked <- aggregate(Mean ~ Bank_Location + Surface.Hit, data = df_prop_hit_type_means, FUN = mean)

View(df_stacked)

stacked_p <- ggplot(df_stacked, aes(fill = Surface.Hit, y = Mean, x = Bank_Location))+
  geom_bar(position = "stack", stat = "identity", color = "black") +
  labs(x = "Bank Location", y = "Proportion of Cover") +
  guides(fill = guide_legend("Cover Type")) +
  theme_bw(base_size = 16) +
  scale_fill_brewer(palette = "Set2")

print(stacked_p)



#new formatting

install.packages("wesanderson")
library(wesanderson)
library(hrbrthemes) # for plot themes
library(gapminder) # for data
library(ggbump) # for the bump plot

W <- wes_palette("Zissou1", 5, type=c("discrete"))

COVER_TYPE_BPw <- df_prop_hit_type_means %>% 
  ggplot(aes(x=factor(Surface.Hit, levels = c('litter', 'Vegetation', 'bare soil', 'downed woody debris', 'water')), y=Mean, fill=Surface.Hit))+
  geom_boxplot()+
  geom_point()+
  labs(x = "Cover Type", y = "Proportion of Cover")+
  stat_summary(fun=mean, geom="point", aes(group = Surface.Hit), position = position_dodge(.9), shape=20, size=2.5, color="yellow", fill="yellow")+
  theme_bw(base_size = 13)+
  theme(legend.position = "none", axis.text.x=element_text(angle=45, hjust=1))+
 scale_color_manual(values= wes_palette("Royal2", n = 5))

?scale_color_manual
print(COVER_TYPE_BPw)

COVER_TYPE_BPw + facet_wrap(~Bank_Location)

```

```{r graphs for hit type by bare soil, litter, vegetation, water, dwd _updated 1/25/23}

#Create general categories based on whether vegetation was hit first, or pin dropped straight to bare ground, litter, water
# To do this, if surface hit is NULL, then hit type is vegetation, otherwise bare soil, litter, dwd, water as designated in the "Surface.Hit" column

vegdf$Surface.Hit <- as.character(vegdf$Surface.Hit)

hit_type <- vegdf %>%
  group_by(sample.bout, Hit.Number, Bank_Location, baseline, Transect, Num_transect_points, Surface.Hit) %>%
  filter(sample.bout =="1") %>%
   mutate(Surface.Hit=recode(Surface.Hit, "NULL" = "Vegetation", "litter" = "Litter", 
                             "bare soil" = "Bare Soil", "water" = "Water", "downed woody debris" = "Woody Debris"))
  
View(hit_type)

n_distinct(hit_type$Surface.Hit) # check number of hit types (veg, litter, bare soil, dwd, water)



#Prepping data file for proportion as response variable
#This final data set is grouped by transects

hit_type$Surface.Hit <- as.factor(hit_type$Surface.Hit)

df.prop_hit_type <- hit_type %>%
  group_by(Hit.Number, Bank_Location, baseline, Transect, Surface.Hit) %>%
  summarise(Count = n()) %>%
  mutate(prop_cover_type = Count/sum(Count)) %>%
  complete(Surface.Hit, fill = list(Count = 0, prop_cover_type = 0)) ## keep all levels of factor and replace NA with zeros for both Count and prop_cover_type

sum(df.prop_hit_type$prop_cover_type[1:5])

View(df.prop_hit_type)


#Make boxplot

p <- df.prop_hit_type %>% ggplot(aes(x=Surface.Hit, y=prop_cover_type))+ 
  geom_boxplot()+
  geom_point()+

  labs(x = "Cover Type", y = "Proportion of Cover")+
  stat_summary(fun=mean, geom="point", aes(group = Surface.Hit), position = position_dodge(.9), shape=20, size=2.5, color="red", fill="red")+
  theme_bw(base_size = 16)+
  theme(axis.text.x=element_text(angle=90, hjust=1))

print(p)

p + facet_wrap(~Bank_Location)


#Need to get the means of each baseline
#The above code currently graphs all 45 transects

df_prop_hit_type_means <- df.prop_hit_type %>%
  group_by(baseline, Bank_Location, Surface.Hit) %>%
  dplyr::summarise(Mean = mean(prop_cover_type))

View(df_prop_hit_type_means)

#Now create new boxplot with baseline means

p2 <- df_prop_hit_type_means %>% ggplot(aes(x=factor(Surface.Hit, levels = c('Litter', 'Vegetation', 'Bare Soil', 'Woody Debris', 'Water')), y=Mean, fill = Surface.Hit))+
  geom_boxplot()+
  geom_point()+
  labs(x = "Cover Type", y = "Proportion of Cover")+
  stat_summary(fun=mean, geom="point", aes(group = Surface.Hit), position = position_dodge(.9), shape=20, size=2.5, color="orange", fill="red")+ #1/25/23 changed group to be surface hit instead of bank location
  theme_bw(base_size = 16)+
  theme(axis.text.x=element_text(angle=45, hjust=1))+
  scale_fill_brewer(palette = "BuGn", name = "Cover Type")+
  theme(legend.position = "none")

print(p2)

p2 + facet_wrap(~Bank_Location)




#formatting

COVER_BP <- df_prop_hit_type_means %>% ggplot(aes(x=factor(Surface.Hit, levels = c('Litter', 'Vegetation', 'Bare Soil', 'Woody Debris', 'Water')), y=Mean, fill = Surface.Hit))+
  geom_boxplot()+
  geom_point(colour="black")+
  labs(x = "Cover Type", y = "Proportion of Cover")+
  stat_summary(fun=mean, geom="point", aes(group = Surface.Hit), position = position_dodge(.9), shape=20, size=2.5, color="orange", fill="orange")+ #1/25/23 changed group to be surface hit instead of bank location
  theme_bw(base_size = 14)+
  theme(axis.text.x=element_text(angle=45, hjust=1))+
  scale_fill_brewer(palette = "BrBG", name = "Cover Type")+
  theme(legend.position = "none")

print(COVER_BP)

COVER_BP + facet_wrap(~Bank_Location)

#Make stacked bar graph by bank location

df_stacked <- aggregate(Mean ~ Bank_Location + Surface.Hit, data = df_prop_hit_type_means, FUN = mean)

View(df_stacked)

Cover_stacked <- ggplot(df_stacked, aes(fill = Surface.Hit, y = Mean, x = Bank_Location))+
  geom_bar(position = "stack", stat = "identity", color = "black") +
  labs(x = "Bank Location", y = "Proportion of Cover") +
  guides(fill = guide_legend("Cover Type")) +
  theme_bw(base_size = 16) + 
  scale_fill_brewer(palette = "BrBG", name = "Cover Type")

print(Cover_stacked)


#Make stacked bar graph by baseline
#Not manually ordered

df_stacked_baseline <- aggregate(Mean ~ baseline + Surface.Hit, data = df_prop_hit_type_means, FUN = mean)

View(df_stacked_baseline)

p <- ggplot(df_stacked_baseline, aes(fill = Surface.Hit, y = Mean, x = baseline))+
  geom_bar(position = "stack", stat = "identity", color = "black") +
  labs(x = "Bank Location", y = "Proportion of Cover") +
  guides(fill = guide_legend("Cover Type")) +
  theme_bw(base_size = 16) + 
  scale_fill_brewer(palette = "Spectral")

print(p)

#FOR HLC REPORT
#Make stacked bar graph by baseline
#Need to manually reorder by baseline and change legend colors 

df_stacked_baseline <- aggregate(Mean ~ baseline + Surface.Hit, data = df_prop_hit_type_means, FUN = mean)

p <- ggplot(df_stacked_baseline, aes(x = factor (baseline, level =c("B03", "B05", "B07", "B10", "B13", "B14", "B15", "B17", "B18")), y = Mean, fill = Surface.Hit, label = round(Mean, digits = 2)))+
  geom_bar(position = "stack", stat = "identity", color = "black") +
  labs(x = "Baseline", y = "Proportion of Cover") +
  guides(fill = guide_legend("Cover Type")) +
  theme_bw(base_size = 16) + 
  scale_fill_brewer(palette = "BuGn", breaks = c("Bare Soil", "Litter", "Vegetation", "Water", "Woody Debris"))

print(p)


#Get some cover type means to report for HLC final report
df_prop_hit_type_means <- df.prop_hit_type %>%
  group_by(baseline, Surface.Hit) %>%
  dplyr::summarise(Mean = mean(prop_cover_type), sd = sd(prop_cover_type))

View(df_prop_hit_type_means)

df_prop_hit_type_means <- df.prop_hit_type %>%
  group_by(Bank_Location, Surface.Hit) %>%
  dplyr::summarise(Mean = mean(prop_cover_type), sd = sd(prop_cover_type))

View(df_prop_hit_type_means)

```



```{r graph WIS}

#Prepping data file for proportion as response variable

vegdf$WIS_GP <- as.factor(vegdf$WIS_GP)

df.props_WIS_veg <- vegdf %>%
  group_by(sample.bout, baseline, baseline.rep, Transect, Hit.Number, Bank_Location, Longevity, Habit, FunctionalGroup, Nativity, Cvalue, WIS_GP) %>%
  filter(sample.bout =="1") %>%
  drop_na(Species.Hit, WIS_GP) %>%  ## drops rows with missing values NA in either Species.Hit or WIS_GP
  summarise(Species.Hit = n()) %>%  ## from the group_by groupings, count the number 
  group_by(baseline, Transect, Bank_Location, WIS_GP) %>%  
  summarise(Species.Hit = sum(Species.Hit)) %>% ## groups by baseline and Bank_location to sum species.Hit
  mutate(prop = Species.Hit/sum(Species.Hit)) %>% ## mutate the df by adding prop that is each #sp/total
  complete(WIS_GP, fill = list(Species.Hit = 0, prop = 0)) ## keep all levels of factor and replace NA with zeros for both Species.Hit and prop

# Check it adds to one with the 5 groups  
sum(df.props_WIS_veg$prop[1:5])
    
View(df.props_WIS_veg)

#get the means across transect (transected is nested within baseline as replication)
df_WIS_means_veg <- df.props_WIS_veg %>%
  group_by(baseline, Bank_Location, WIS_GP) %>%
  dplyr::summarise(Mean = mean(prop))

View(df_WIS_means_veg)

#get the means again but average bank location as well
df_WIS_means_veg2 <- df.props_WIS_veg %>%
  group_by(baseline, WIS_GP) %>%
  dplyr::summarise(Mean = mean(prop))

View(df_WIS_means_veg2)

#boxplot without bank location
WIS_veg1 <- df_WIS_means_veg2 %>% 
  mutate(WIS_GP = fct_relevel(WIS_GP, "UPL", 'FACU', 'FAC', 'FACW', 'OBL')) %>% 
  ggplot(aes(x=factor(WIS_GP), y=Mean, fill=WIS_GP))+ 
  geom_boxplot()+
    geom_point()+
    labs(x = "Wetland Indicator Status", y = "Proportion of Cover")+
    stat_summary(fun=mean, geom="point", aes(group = WIS_GP), position = position_dodge(.9), shape=20, size=2.5, color="orange", fill="orange")+
    theme_bw(base_size = 10)+
    theme(legend.position = "none", axis.text.x=element_text(angle=45, hjust=1))+
    scale_fill_brewer(palette = "BuGn")
print(WIS_veg1)

#box plot for bank location
WIS_vegBL <- df_WIS_means_veg %>% 
  mutate(WIS_GP = fct_relevel(WIS_GP, "UPL", 'FACU', 'FAC', 'FACW', 'OBL')) %>% 
  ggplot(aes(x=factor(WIS_GP), y=Mean, fill=WIS_GP))+ 
  geom_boxplot()+
    geom_point()+
    labs(x = "Wetland Indicator Status", y = "Proportion of Cover")+
    stat_summary(fun=mean, geom="point", aes(group = WIS_GP), position = position_dodge(.9), shape=20, size=2.5, color="orange", fill="orange")+
    theme_bw(base_size = 10)+
    theme(legend.position = "none", axis.text.x=element_text(angle=45, hjust=1))+
    scale_fill_brewer(palette = "BuGn")
WIS_BL_Veg <- WIS_vegBL + facet_wrap(~Bank_Location)
print(WIS_BL_Veg)

#Stacked graph _ AI 9/27

df_stacked_v <- aggregate(Mean ~ Bank_Location + WIS_GP , data = df_WIS_means_veg, FUN = mean)

#View(df_stacked)

St_WIS_vg <- df_stacked_v %>%
  mutate(WIS_GP = fct_relevel(WIS_GP, "UPL", 'FACU', 'FAC', 'FACW', 'OBL')) %>%
  ggplot(aes(fill = WIS_GP, y = Mean, x = Bank_Location))+
  geom_bar(position = "stack", stat = "identity", color = "black") +
  labs(x = "Bank Location", y = "Proportion of Cover") +
  guides(fill = guide_legend("WIS")) +
  theme_bw(base_size = 16) +
  scale_fill_brewer(palette = "BuGn")

print(St_WIS_vg)

#stacked graph for baseline

df_stacked_WIS_baseline <- aggregate(prop ~ baseline + WIS_GP, data = df.props_WIS_veg, FUN = mean)

View(df_stacked_WIS_baseline)

df_stacked_WIS_baseline$baseline <- as.character(df_stacked_WIS_baseline$baseline)

df_stacked_WIS_baseline %>%
  mutate(WIS_GP = fct_relevel(WIS_GP, "UPL", 'FACU', 'FAC', 'FACW', 'OBL')) %>%
  mutate(baseline = fct_relevel(baseline, "B3", "B5", "B7", "B10", "B13", "B14", "B15", "B17", "B18")) %>%
  ggplot(aes(fill = WIS_GP, y = prop, x = baseline))+
  geom_bar(position = "stack", stat = "identity", color = "black") +
  labs(x = "Baseline", y = "Proportion of Cover") +
  guides(fill = guide_legend("WIS")) +
  theme_bw(base_size = 16)+
  scale_fill_brewer(palette = "BuGn")
 

```

```{r graph nativity}


#Prepping data file for proportion as response variable

vegdf$Nativity <- as.factor(vegdf$Nativity)

df.props_Nativity_veg <- vegdf %>%
  group_by(sample.bout, baseline, baseline.rep, Transect, Hit.Number, Bank_Location, Longevity, Habit, FunctionalGroup, Nativity, WIS_GP) %>%
  filter(sample.bout =="1") %>%
  drop_na(Species.Hit, Nativity) %>%  ## drops rows with missing values NA in either Species.Hit or WIS_GP
  summarise(Species.Hit = n()) %>%  ## from the group_by groupings, count the number 
  group_by(baseline, Transect, Bank_Location, Nativity) %>%  
  summarise(Species.Hit = sum(Species.Hit)) %>% ## groups by baseline and Bank_location to sum species.Hit
  mutate(prop = Species.Hit/sum(Species.Hit)) %>% ## mutate the df by adding prop that is each #sp/total
  complete(Nativity, fill = list(Species.Hit = 0, prop = 0)) ## keep all levels of factor and replace NA with zeros for both Species.Hit and prop

# Check it adds to one with the 2 groups (native & introduced)
sum(df.props_Nativity_veg$prop[1:2])
    
#View(df.props_Nativity_veg)

#get the means across transect (transected is nested within baseline as replication)
df_Nativ_means_veg <- df.props_Nativity_veg %>%
  group_by(baseline, Bank_Location, Nativity) %>%
  dplyr::summarise(Mean = mean(prop))

View(df_Nativ_means_veg)


#get the means again but average bank location as well
df_nativ_means_veg2 <- df.props_Nativity_veg %>%
  group_by(baseline, Nativity) %>%
  dplyr::summarise(Mean = mean(prop))

View(df_nativ_means_veg2)

#boxplot without bank location

Nativ_veg1 <- df_nativ_means_veg2 %>% 
  ggplot(aes(x=factor(Nativity), y=Mean, fill=Nativity))+ 
  geom_boxplot()+
    geom_point()+
    labs(x = "Nativity", y = "Proportion of Cover")+
    stat_summary(fun=mean, geom="point", aes(group = Nativity), position = position_dodge(.9), shape=20, size=2.5, color="orange", fill="orange")+
    theme_bw(base_size = 10)+
    theme(legend.position = "none", axis.text.x=element_text(angle=45, hjust=1))+
    scale_fill_brewer(palette = "BuGn")
print(Nativ_veg1)

#bank location
Nativ_veg <- df_Nativ_means_veg %>% 
  ggplot(aes(x=factor(Nativity), y=Mean, fill=Nativity))+ 
  geom_boxplot()+
    geom_point()+
    labs(x = "Nativity", y = "Proportion of Cover")+
    stat_summary(fun=mean, geom="point", aes(group = Nativity), position = position_dodge(.9), shape=20, size=2.5, color="orange", fill="orange")+
    theme_bw(base_size = 10)+
    theme(legend.position = "none", axis.text.x=element_text(angle=45, hjust=1))+
    scale_fill_brewer(palette = "BuGn")
print(Nativ_veg)

Nativ_BL_Veg <- Nativ_veg + facet_wrap(~Bank_Location)
print(Nativ_BL_Veg)

#Stacked graph _ AI 9/27

df_Nativ_stacked_v <- aggregate(Mean ~ Bank_Location + Nativity , data = df_Nativ_means_veg, FUN = mean)

#View(df_Nativ_stacked_v)

St_Nativ_vg <- df_Nativ_stacked_v %>%
  ggplot(aes(fill = Nativity, y = Mean, x = Bank_Location))+
  geom_bar(position = "stack", stat = "identity", color = "black") +
  labs(x = "Bank Location", y = "Proportion of Cover") +
  guides(fill = guide_legend("Nativity")) +
  theme_bw(base_size = 16) +
  scale_fill_brewer(palette = "BuGn")

print(St_Nativ_vg)


```

```{r graph functional group}

#Prepping data file for proportion as response variable

vegdf$FunctionalGroup2 <- as.factor(vegdf$FunctionalGroup2)

df.props_FG_veg <- vegdf %>%
     filter(FunctionalGroup2 !="NA Forb") %>% #remove before prop is calculated
  filter(FunctionalGroup2 !="NA NA") %>% 
  filter(FunctionalGroup2 !="Variable Forb") %>%
  group_by(sample.bout, baseline, baseline.rep, Transect, Hit.Number, Bank_Location, Longevity, Habit, FunctionalGroup2, Nativity, WIS_GP) %>%
  filter(sample.bout =="1") %>%
  drop_na(Species.Hit, FunctionalGroup2) %>%  ## drops rows with missing values NA in either Species.Hit or WIS_GP
  summarise(Species.Hit = n()) %>%  ## from the group_by groupings, count the number 
  group_by(baseline, Transect, Bank_Location, FunctionalGroup2) %>%  
  summarise(Species.Hit = sum(Species.Hit)) %>% ## groups by baseline and Bank_location to sum species.Hit
  mutate(propFG = Species.Hit/sum(Species.Hit)) %>% ## mutate the df by adding prop that is each #sp/total
  complete(FunctionalGroup2, fill = list(Species.Hit = 0, propFG = 0)) %>% ## keep all levels of factor and replace NA with zeros for both Species.Hit and prop
   filter(FunctionalGroup2 !="NA Forb") %>%  #remove after complete function so they aren't included in graphs
  filter(FunctionalGroup2 !="NA NA") %>% 
  filter(FunctionalGroup2 !="Variable Forb")

# Check it adds to one with the # groups of variable of interest
sum(df.props_FG_veg$propFG[1:5]) 
    
View(df.props_FG_veg)

#get the means across transect (transected is nested within baseline as replication)
df_FG_means_veg <- df.props_FG_veg %>%
  group_by(baseline, Bank_Location, FunctionalGroup2) %>%
  dplyr::summarise(Mean = mean(propFG))

#View(df_FG_means_veg)

#get the means again but average bank location as well
df_FG_means_veg2 <- df.props_FG_veg %>%
  group_by(baseline, FunctionalGroup2) %>%
  dplyr::summarise(Mean = mean(propFG))

View(df_FG_means_veg2)

#boxplot without bank location
FG_veg1 <- df_FG_means_veg2 %>% 
  ggplot(aes(x=factor(FunctionalGroup2), y=Mean, fill=FunctionalGroup2))+ 
  geom_boxplot()+
    geom_point()+
    labs(x = "Functional Group", y = "Proportion of Cover")+
    stat_summary(fun=mean, geom="point", aes(group = FunctionalGroup2), position = position_dodge(.9), shape=20, size=2.5, color="orange", fill="orange")+
    theme_bw(base_size = 10)+
    theme(legend.position = "none", axis.text.x=element_text(angle=45, hjust=1))+
    scale_fill_brewer(palette = "BuGn")
print(FG_veg1)

#Seperate by Bank location
FG_veg <- df_FG_means_veg %>% 
  ggplot(aes(x=factor(FunctionalGroup2), y=Mean, fill=FunctionalGroup2))+ 
  geom_boxplot()+
    geom_point()+
    labs(x = "Functional Group", y = "Proportion of Cover")+
    stat_summary(fun=mean, geom="point", aes(group = FunctionalGroup2), position = position_dodge(.9), shape=20, size=2.5, color="orange", fill="orange")+
    theme_bw(base_size = 10)+
    theme(legend.position = "none", axis.text.x=element_text(angle=45, hjust=1))+
    scale_fill_brewer(palette = "BuGn")
print(FG_veg)

FG_BL_Veg <- FG_veg + facet_wrap(~Bank_Location)
print(FG_BL_Veg)

#Stacked graph _ AI 9/27

df_fg_stacked_v <- aggregate(Mean ~ Bank_Location + FunctionalGroup2 , data = df_FG_means_veg, FUN = mean)

#View(df_Nativ_stacked_v)

St_FG_vg <- df_fg_stacked_v %>%
  ggplot(aes(fill = FunctionalGroup2, y = Mean, x = Bank_Location))+
  geom_bar(position = "stack", stat = "identity", color = "black") +
  labs(x = "Bank Location", y = "Proportion of Cover") +
  guides(fill = guide_legend("Functional Group")) +
  theme_bw(base_size = 16) +
  scale_fill_brewer(palette = "BuGn")

print(St_FG_vg)


```

```{r spider chart}

#get proportions of short-lived, long-lived, FAC,  FACU/UPL, FACW/OBL, forb and graminoid for both native and introduced --> of the native, what proportion (out of whole?) & vice versa
#will need to remove any row that doesn't have all info listed (including Juncus sp.)
vegdf$Nativity <- as.factor(vegdf$Nativity)
vegdf$WIS_Grouped <- as.factor(seedbankdf$WIS_Grouped)


#filter(sample.bout !="2") %>%

#count of native and introduced
native_count_v <- vegdf %>% 
  drop_na(Species.Hit, WIS_Grouped, Habit, Longevity_2, Nativity) %>%
  filter(sample.bout =="1") %>%
  filter(Longevity_2 !="Variable") %>%
  group_by(Nativity) %>% 
  summarise(count = n())

view(native_count_v)

#INTRODUCED
#WIS
introd_WIS_count_v <- vegdf %>% 
  drop_na(Species.Hit, WIS_Grouped, Habit, Longevity_2, Nativity) %>%
  filter(sample.bout =="1") %>%
  filter(Longevity_2 !="Variable") %>%
  subset(Nativity == "Introduced") %>%
  group_by(WIS_Grouped) %>% 
  summarise(count = n())
  
view(introd_WIS_count_v)

#Longevity
introd_longevity_count_v <- vegdf %>% 
  drop_na(Species.Hit, WIS_Grouped, Habit, Longevity_2, Nativity) %>%
  filter(sample.bout =="1") %>%
  filter(Longevity_2 !="Variable") %>%
  subset(Nativity == "Introduced") %>%
  group_by(Longevity_2) %>% 
  summarise(count = n())
  
view(introd_longevity_count_v)

#habit
introd_habit_count_v <- vegdf %>% 
  drop_na(Species.Hit, WIS_Grouped, Habit, Longevity_2, Nativity) %>%
  filter(sample.bout =="1") %>%
  filter(Longevity_2 !="Variable") %>%
  subset(Nativity == "Introduced") %>%
  group_by(Habit) %>% 
  summarise(count = n())
  
view(introd_habit_count_v)

#NATIVE counts
#WIS
native_WIS_count_v <- vegdf %>% 
  drop_na(Species.Hit, WIS_Grouped, Habit, Longevity_2, Nativity) %>%
  filter(sample.bout =="1") %>%
  filter(Longevity_2 !="Variable") %>%
  subset(Nativity == "Native") %>%
  group_by(WIS_Grouped) %>% 
  summarise(count = n())
  
view(native_WIS_count_v)

#Longevity
native_longevity_count_v <- vegdf %>% 
  drop_na(Species.Hit, WIS_Grouped, Habit, Longevity_2, Nativity) %>%
  filter(sample.bout =="1") %>%
  filter(Longevity_2 !="Variable") %>%
  subset(Nativity == "Native") %>%
  group_by(Longevity_2) %>% 
  summarise(count = n())
  
view(native_longevity_count_v)

#Habit
native_habit_count_v <- vegdf %>% 
  drop_na(Species.Hit, WIS_Grouped, Habit, Longevity_2, Nativity) %>%
  filter(sample.bout =="1") %>%
  filter(Longevity_2 !="Variable") %>%
  subset(Nativity == "Native") %>%
  group_by(Habit) %>% 
  summarise(count = n())
  
view(native_habit_count_v)

#build a data frame

#not this one :/
metric <- c("Short_lived", "Long_lived", "OBL_FACW", "FAC", "UPL_FACU", "FORB", "Graminoid", "Woody")
Introduced <- c(12, 96, 9, 6, 93, 51, 21, 36)
Native <- c(19, 216, 167, 42, 26, 51, 138, 46)

DF_Spider_v <- data.frame(metric, Introduced, Native)
  
#build a data frame with counts
#this one
Nativity <- c("Native", "Introduced")
Shortlived <- c(5, 26)
Longlived <- c(243, 531)
OBL_FACW <- c(179, 3)
FAC <- c(38, 11)
UPL_FACU <- c(31, 543)
Forb <- c(54, 157)
Graminoid <- c(142, 367)
Woody <- c(52, 33)

DF_Spider_2v <- data.frame(Nativity, Shortlived, Longlived, OBL_FACW, FAC, UPL_FACU, Forb, Graminoid, Woody)

view(DF_Spider_2v)

#pivot and calc proportions
tv<-t(DF_Spider_2v)
tv<-as.data.frame(tv)
tv<-janitor::row_to_names(tv,row_number=1)
tv$'1'<-1
tv$'2'<-0
tv$Native<-as.numeric(tv$Native)/248
tv$Introduced<-as.numeric(tv$Introduced)/557
tv <- tv[, c("1", "2", "Native",'Introduced')] # leave the row index blank to keep all rows
DF_Spider_2v<-t(tv)
DF_Spider_2v<-as.data.frame(DF_Spider_2v)
view(DF_Spider_2v)

view(DF_Spider_2v)

# plot with default options:
radarchart(DF_Spider_2v)

# Set graphic colors
library(RColorBrewer)
coul <- brewer.pal(3, "Dark2")
colors_border <- coul
library(scales)
colors_in <- alpha(coul,0.3)

#customize
radarchart(DF_Spider_2v, axistype=1 , 
    title = "Vegetation",
    #custom polygon
    pcol=colors_border , pfcol=colors_in , plwd=4 , plty=1,
    #custom the grid
    cglcol="darkgrey", cglty=1, axislabcol="darkgrey", caxislabels=seq(0,1), cglwd=0.8,
    #custom labels
    vlcex=1)

#add legend
legend(x=.6, y=1.4, legend = rownames(DF_Spider_2[-c(1,2),]), bty = "n", pch=20 , col=colors_in , text.col = "darkgrey", cex=1.2, pt.cex=3)




#example
# Construct the data set (Data from Marvel.com)
data <- data.frame(Strength = c(7, 0, 6),
                   Speed = c(7, 0, 5),
                   Intelligence = c(7, 0, 6),
                   Fighting_Skills = c(7, 0, 4),
                   Energy = c(7, 0, 6),
                   Durability = c(7, 0, 6))

radarchart(data, 
           seg = 7,  # Number of axis segments
           title = "Iron Man Radar Chart",
           pfcol = scales::alpha("gray", 0.3),
           plwd = 2)


# Radar chart with multiple overlapping individuals

# Construct the data set
data ＜- data.frame(Strength = c(7, 0, 6, 7, 4, 3),
                   Speed = c(7, 0, 5, 7, 3, 2),
                   Intelligence = c(7, 0, 6, 2, 4, 3),
                   Fighting_Skills = c(7, 0, 4, 4, 4, 6),
                   Energy = c(7, 0, 6, 6, 1, 1),
                   Durability = c(7, 0, 6, 6, 3, 3),
                   row.names = c("max", "min", "Iron Man", "Thor", 
                                 "Spiderman", "Captain America"))

# Define fill colors
colors_fill ＜- c(scales::alpha("gray", 0.1),
                 scales::alpha("gold", 0.1),
                 scales::alpha("tomato", 0.2),
                 scales::alpha("skyblue", 0.2))

# Define line colors
colors_line ＜- c(scales::alpha("darkgray", 0.9),
                scales::alpha("gold", 0.9),
                scales::alpha("tomato", 0.9),
                scales::alpha("royalblue", 0.9))

# Create plot
radarchart(data, 
           seg = 7,  # Number of axis segments
           title = "Avengers Radar Chart",
           pcol = colors_line,
           pfcol = colors_fill,
           plwd = 4)

# Add a legend
legend(x=0.6, 
       y=1.35, 
       legend = rownames(data[-c(1,2),]), 
       bty = "n", pch=20 , col = colors_line, cex = 1.05, pt.cex = 3)
```

```{r graph rank abundance curve}

#Prepping data file for proportion as response variable

vegdf$VegHit_SoilSurfaceHit <- as.factor(vegdf$VegHit_SoilSurfaceHit)

df.props_RankAbund_veg <- vegdf %>%
  group_by(sample.bout, baseline, baseline.rep, Transect, Hit.Number, Bank_Location, Species.Hit, VegHit_SoilSurfaceHit) %>%
  filter(sample.bout =="1") %>%
  subset(VegHit_SoilSurfaceHit!="bare soil" & VegHit_SoilSurfaceHit!="downed woody debris"
         & VegHit_SoilSurfaceHit!="litter" & VegHit_SoilSurfaceHit!="rock" & VegHit_SoilSurfaceHit!="water" & VegHit_SoilSurfaceHit!="NULL") %>%
  drop_na(Species.Hit, VegHit_SoilSurfaceHit) %>%  ## drops rows with missing values NA in either Species.Hit 
  summarise(Species.Hit = n()) %>%  ## from the group_by groupings, count the number 
  group_by(baseline, Transect, Bank_Location, VegHit_SoilSurfaceHit) %>%  
  summarise(Species.Hit = sum(Species.Hit)) %>% ## groups by baseline and Bank_location to sum species.Hit
  mutate(prop = Species.Hit/sum(Species.Hit)) %>% ## mutate the df by adding prop that is each #sp/total
  complete(VegHit_SoilSurfaceHit, fill = list(Species.Hit = 0, prop = 0)) %>% ## keep all levels of factor and replace NA with zeros for both Species.Hit and prop
  subset(VegHit_SoilSurfaceHit!="bare soil" & VegHit_SoilSurfaceHit!="downed woody debris"
         & VegHit_SoilSurfaceHit!="litter" & VegHit_SoilSurfaceHit!="rock" & VegHit_SoilSurfaceHit!="water" & VegHit_SoilSurfaceHit!="NULL") #remove after complete function so they aren't included in graphs (same as with FG)


# Check it adds to one with the 5 groups  
sum(df.props_RankAbund_veg$prop[1:58])
    
View(df.props_RankAbund_veg)

#get the means across transect (transected is nested within baseline as replication)
df_RankAbund_means_veg <- df.props_RankAbund_veg %>%
  group_by(baseline, Bank_Location, VegHit_SoilSurfaceHit) %>%
  dplyr::summarise(Mean = mean(prop))

View(df_RankAbund_means_veg)

#get the means again but average bank location as well
df_RankAbund_means_veg2 <- df.props_RankAbund_veg %>%
  group_by(baseline, VegHit_SoilSurfaceHit) %>%
  dplyr::summarise(Mean = mean(prop))

View(df_RankAbund_means_veg2)


# means again but average across all to get most common species
df_RankAbund_means_veg3 <- df.props_RankAbund_veg %>%
  group_by(VegHit_SoilSurfaceHit) %>%
  dplyr::summarise(Mean = mean(prop))

Common_veg_species <- df_RankAbund_means_veg3 %>%
  filter(Mean > 0.0099) %>%
  arrange(Mean)


View(Common_veg_species)

#boxplot without bank location (not needed)

RankAbund_veg1 <- df_RankAbund_means_veg2 %>%
  arrange(Mean) %>%
  filter(VegHit_SoilSurfaceHit == "Bromus inermis"
         | VegHit_SoilSurfaceHit == "Phalaris arundinacea" 
         | VegHit_SoilSurfaceHit == "Elymus repens"
         | VegHit_SoilSurfaceHit == "Rhamnus cathartica" 
         | VegHit_SoilSurfaceHit == "Dactylis glomerata" 
         | VegHit_SoilSurfaceHit == "Cirsium arvense"
         | VegHit_SoilSurfaceHit == "Taraxacum officinale" 
         | VegHit_SoilSurfaceHit == "Parthenocissus vitacea" 
         | VegHit_SoilSurfaceHit == "Convolvulus arvensis"
         | VegHit_SoilSurfaceHit == "Symphyotrichum lanceolatum ssp. hesperium" 
         | VegHit_SoilSurfaceHit == "Schedonorus arundinaceus" 
         | VegHit_SoilSurfaceHit == "Carex emoryi"
         | VegHit_SoilSurfaceHit == "Symphoricarpos occidentalis" 
         | VegHit_SoilSurfaceHit == "Prunus virginiana")  %>%
  mutate(VegHit_SoilSurfaceHit = fct_relevel(VegHit_SoilSurfaceHit, "Bromus inermis", "Phalaris arundinacea", "Elymus repens", "Rhamnus cathartica", "Dactylis glomerata", "Cirsium arvense", "Taraxacum officinale",  "Parthenocissus vitacea", "Convolvulus arvensis", "Symphyotrichum lanceolatum ssp. hesperium", "Schedonorus arundinaceus", "Carex emoryi", "Symphoricarpos occidentalis", "Prunus virginiana")) %>% 
  ggplot(aes(x=factor(VegHit_SoilSurfaceHit), y=Mean, fill=VegHit_SoilSurfaceHit))+ 
  geom_boxplot()+
    geom_point()+
    labs(x = "Species", y = "Proportion of Cover")+
    stat_summary(fun=mean, geom="point", aes(group = VegHit_SoilSurfaceHit), position = position_dodge(.9), shape=20, size=2.5, color="purple", fill="purple")+
    theme_bw(base_size = 10)+
    theme(legend.position = "none", axis.text.x=element_text(angle=45, hjust=1))+
    scale_fill_brewer(palette = "RdBu")


print(RankAbund_veg1)
 

```




```{r stats for WIS with WIS and bank location interaction}

#Need to run code in chunk above named "r graph WIS by bank location" that creates the data file df.props_WIS_veg

#Create competing models
view(df.props_WIS_veg)
str(df.props_WIS_veg)


#Anova
lmer_gaus_null <- lmer(prop ~ 1 + (1|baseline) + (1|Transect:baseline), data = df.props_WIS_veg) #intercept only, just models variation across baselines and transects, no accounting for variation explained by WIS
lmer_gaus1 <- lmer(prop ~ WIS_GP + (1|baseline) + (1|Transect:baseline), data = df.props_WIS_veg) #add in variation explained by WIS
lmer_gaus2 <- lmer(prop ~ WIS_GP + Bank_Location + (1|baseline) + (1|Transect:baseline), data = df.props_WIS_veg) #add in variation explained by bank location
lmer_gaus3 <- lmer(prop ~ WIS_GP + Bank_Location + WIS_GP*Bank_Location + (1|baseline) + (1|Transect:baseline), data = df.props_WIS_veg) #add in interaction term
lmer_gaus4 <- lmer(prop ~ WIS_GP + Bank_Location + WIS_GP*Bank_Location + (1|baseline), data = df.props_WIS_veg) #Remove random effect of transect within baseline

AIC(lmer_gaus_null, lmer_gaus1,lmer_gaus2,lmer_gaus3, lmer_gaus4) #code to run AIC; lowest number is best fit; typically considered that difference should be at least 2 to be considered a meaningful improvement of fit

summary(lmer_gaus1) #Get model output
summary(lmer_gaus2) #Get model output
summary(lmer_gaus3) #Get model output
summary(lmer_gaus4) #Get model output

WIS_veg_model_summary<-as.data.frame(coef(summary(lmer_gaus4))) #put coefficients into dataframe

#write.csv(WIS_veg_model_summary, 'WIS_veg_model_summary.csv', row.names = TRUE) #CSV, keeping names in index


library(lmerTest)
#Different ways to visualize the distribution of the data; the raw data (distribution of y) is not normally distributed but the model fit
#(with y conditional on x) looks decent (although still violates normality) based on qqplot and distribution of fitted versus residuals

#Can also get the output for lines 599-603 below using sjPlot code 

proportion_WIS_gauss <- df.props_WIS_veg$prop #Histogram showing lots of zeroes, positive skew 
hist(proportion_WIS_gauss)#shows skew. L shaped-distrib/right skewed-> not normal
qqnorm(df.props_WIS_veg$prop) #use to visualize whether raw data are normally distributed
#raw data; shows a lot of 0s and a lot of 1's; normal otherwise
#if normally distributed this would like a straight line
qqnorm(resid(lmer_gaus4))     #Use to visualize whether model residuals vs predicted are normally distributed 
#good fit (meaning model doesn't violate normality assumptions) if dots fit along a line; rare to get ecological data that fits this line perfectly
plot(lmer_gaus4)              #Use to visualize whether model residuals vs predicted are normally distributed
#this shows what happens to variance around the mean as you go from smaller to larger numbers
#well fit model that doesn't violate assumptions would look like equal smattering of rows of dots
#not about distribution but about if variances are equal across the dataset
#here we see that variance increases from left to right, and on left hand side, more positive; more evenly distributed to the right
#model violates assumption of homogeniety of variances



#Choose lmer_gaus_upper4 based on AIC and run diagnostics, output, pairwise comparisons

#effectsize::standardize(lmer_gaus_upper2) %>% summary()
plot_residuals(lmer_gaus4) #who knows
plot_model(lmer_gaus4, type = "diag") #same as line 919
sjPlot::plot_model(lmer_gaus4, type = "est", show.values = T) # comparing to intercept; quick data viz; this info would go into table

sjPlot::tab_model(lmer_gaus4, df.method = "satterthwaite", title = "Proportion WIS in Vegetation", dv.labels = "Proportion Cover") #another table showing that info

emmeans(lmer_gaus4, df.method = "satterthwaite", pairwise ~ WIS_GP | Bank_Location, adjust = "tukey") #this first part is what I would use to report in summary table; to build table off of this
#emmean is essentially the same as estimate

#export
WIS_emmeans_output<-as.data.frame(emmeans(lmer_gaus4, df.method = "satterthwaite", pairwise ~ WIS_GP | Bank_Location, adjust = "tukey")) #data frame
write_xlsx(WIS_emmeans_output, 'WIS_emmeans_output.xlsx')

#second part (contrasts), pay attn to what is significant; pick and choose from the significant ones, the ones that are BIOLOGICALLY meaningful
#when i decide which ones I care about, that is what goes into the text; would not be a table for this

emmip(lmer_gaus4, WIS_GP ~ Bank_Location, CIs = TRUE) #graph of interaction between bank location and WIS #need to have CI's for the thesis--> how can i make it look better? #work on aesthetics
emmip(lmer_gaus4, WIS_GP ~ Bank_Location) #graph of interaction between bank location and WIS #might be better to show w/out CI for talk
#y axis: proportional cover, model fitted estimate of that; prop of 5 diff groups depends on bank location; lines connecting them is showing interaction

#customizations
emmip(lmer_gaus4, WIS_GP ~ Bank_Location, CIs = TRUE, linearg = list(),
      CIarg = list(lwd = 1, alpha = 1)) +
  ggplot2::theme_bw() +
  ylab("Linear Prediction of Cover Wetland Indicator Status (WIS) Proportion") +       
  xlab("Bank Location") +
  ggtitle("Vegetation")

emmip(lmer_gaus4, WIS_GP ~ Bank_Location, linearg = list(),
      CIarg = list(lwd = 1, alpha = 1)) +
  ggplot2::theme_bw() +
  ylab("Linear Prediction of Cover Wetland Indicator Status (WIS) Proportion") +       
  xlab("Bank Location") +
  ggtitle("Vegetation")

as.data.frame(df_emmeans) #not sure if this works 
view(df_emmeans)

```

```{r nativity stats with nativity and bank location interaction}

#Need to run code in chunk above named "r graph native/intro by bank location" that creates the data file df.props_Nativity_veg 

#Create competing models

lmer_gaus_null <- lmer(prop ~ 1 + (1|baseline) + (1|Transect:baseline), data = df.props_Nativity_veg) #intercept only, just models variation across baselines and transects, no accounting for variation explained by nativity
lmer_gaus_native_1 <- lmer(prop ~ Nativity + (1|baseline) + (1|Transect:baseline), data = df.props_Nativity_veg) #add in variation explained by nativity
lmer_gaus_native_2 <- lmer(prop ~ Nativity + Bank_Location + (1|baseline) + (1|Transect:baseline), data = df.props_Nativity_veg) #add in variation explained by bank location
lmer_gaus_native_3 <- lmer(prop ~ Nativity + Bank_Location + Nativity*Bank_Location + (1|Transect:baseline) + (1|Transect:baseline), data = df.props_Nativity_veg) #add in interaction term
lmer_gaus_native_4 <- lmer(prop ~ Nativity + Bank_Location + Nativity*Bank_Location + (1|Transect:baseline), data = df.props_Nativity_veg) #Remove random effect of transect within baseline

AIC(lmer_gaus_native_1, lmer_gaus_native_2, lmer_gaus_native_3, lmer_gaus_native_4)

summary(lmer_gaus_native_1)
summary(lmer_gaus_native_2)
summary(lmer_gaus_native_3)
summary(lmer_gaus_native_4)


N_veg_model_summary<-as.data.frame(coef(summary(lmer_gaus_native_4))) #put coefficients into dataframe

write.csv(N_veg_model_summary, 'N_veg_model_summary.csv', row.names = TRUE) #CSV, keeping names in index


#Different ways to visualize distribution of the raw data and model fitted data (y conditional on x)

proportion_Nativity_gauss <- df.props_Nativity_veg$prop #Histogram showing lots of zeroes and ones 
hist(proportion_Nativity_gauss)
qqnorm(df.props_Nativity_veg$prop) #use to visualize whether raw data are normally distributed
qqnorm(resid(lmer_gaus_native_4))     #Use to visualize whether model residuals vs predicted are normally distributed
plot(lmer_gaus_native_4)              #Use to visualize whether model residuals vs predicted are normally distributed

qqnorm(resid(lmer_gaus_native_4)) #Use to visualize whether normally distributed
plot(lmer_gaus_native_4)


#Choose lmer_gaus_native_4 based on AIC and run diagnostics, output, pairwise comparisons

#effectsize::standardize(lmer_gaus_upper2) %>% summary()
plot_residuals(lmer_gaus_native_4)
plot_model(lmer_gaus_native_4, type = "diag")
sjPlot::plot_model(lmer_gaus_native_4, type = "est", show.values = T)

sjPlot::tab_model(lmer_gaus_native_4, df.method = "satterthwaite", title = "Proportion Native and Introduced in Vegetation", dv.labels = "Proportion Cover")

emmeans(lmer_gaus_native_4, df.method = "satterthwaite", pairwise ~ Nativity | Bank_Location, adjust = "tukey")

#export
nativ_emmeans_output<-as.data.frame(emmeans(lmer_gaus_native_4, df.method = "satterthwaite", pairwise ~ Nativity | Bank_Location, adjust = "tukey")) #data frame
write_xlsx(nativ_emmeans_output, 'nativ_emmeans_output.xlsx')

emmip(lmer_gaus_native_4, Nativity~ Bank_Location, CIs = TRUE)

#customizations
emmip(lmer_gaus_native_4, Nativity ~ Bank_Location, CIs = TRUE, linearg = list(),
      CIarg = list(lwd = 1, alpha = 1)) +
  ggplot2::theme_bw() +
  ylab("Linear Prediction of Cover Nativity Proportion") +       
  xlab("Bank Location") +
  ggtitle("Vegetation")

```

```{r stats for functional group by bank location interaction}

#Need to run code in chunk above named "r graph functional groups by bank location" that creates the data file df.props_FG
view(df.props_FG_veg)
#Create competing models

lmer_gaus_null <- lmer(propFG ~ 1 + (1|baseline) + (1|Transect:baseline), data = df.props_FG_veg)
lmer_gaus_fg_1 <- lmer(propFG ~ FunctionalGroup2 + (1|baseline) + (1|Transect:baseline), data = df.props_FG_veg)
lmer_gaus_fg_2 <- lmer(propFG ~ FunctionalGroup2 + Bank_Location + (1|baseline) + (1|Transect:baseline), data = df.props_FG_veg)
lmer_gaus_fg_3 <- lmer(propFG ~ FunctionalGroup2 + Bank_Location + FunctionalGroup2*Bank_Location + (1|Transect:baseline) + (1|Transect:baseline), data = df.props_FG_veg)
lmer_gaus_fg_4 <- lmer(propFG ~ FunctionalGroup2 + Bank_Location + FunctionalGroup2*Bank_Location + (1|baseline), data = df.props_FG_veg)

AIC(lmer_gaus_null, lmer_gaus_fg_1, lmer_gaus_fg_2,lmer_gaus_fg_3, lmer_gaus_fg_4) 

summary(lmer_gaus_fg_1)
summary(lmer_gaus_fg_2)
summary(lmer_gaus_fg_3)
summary(lmer_gaus_fg_4) #using this model even though AIC isn't lowest

FG_veg_model_summary<-as.data.frame(coef(summary(lmer_gaus_fg_4))) #put coefficients into dataframe

#write.csv(FG_veg_model_summary, 'FG_veg_model_summary.csv', row.names = TRUE) #CSV, keeping names in index

#Different ways to visualize distribution of the raw data and model fitted data (y conditional on x)

proportion_fg_gauss <- df.props_FG$propFG #Histogram showing lots of zeroes and ones 
hist(proportion_fg_gauss)
qqnorm(df.props_FG$propFG) #use to visualize whether raw data are normally distributed
qqnorm(resid(lmer_gaus_fg_4))     #Use to visualize whether model residuals vs predicted are normally distributed
plot(lmer_gaus_fg_4)              #Use to visualize whether model residuals vs predicted are normally distributed


#Choose lmer_gaus_fg_4 based on AIC and run diagnostics, output, pairwise comparisons

#effectsize::standardize(lmer_gaus_upper2) %>% summary()
plot_residuals(lmer_gaus_fg_4)
plot_model(lmer_gaus_fg_4, type = "diag")
sjPlot::plot_model(lmer_gaus_fg_4, type = "est", show.values = T)

sjPlot::tab_model(lmer_gaus_fg_4, df.method = "satterthwaite", title = "Proportion of Functional Groups in Vegetation", dv.labels = "Proportion Cover")

emmeans(lmer_gaus_fg_4, df.method = "satterthwaite", pairwise ~ FunctionalGroup2 | Bank_Location, adjust = "tukey")

#export
FG_emmeans_output<-as.data.frame(emmeans(lmer_gaus_fg_4, df.method = "satterthwaite", pairwise ~ FunctionalGroup2 | Bank_Location, adjust = "tukey")) #data frame
write_xlsx(FG_emmeans_output, 'FG_emmeans_output.xlsx')

emmeans(lmer_gaus_fg_4, df.method = "satterthwaite", pairwise ~ FunctionalGroup | Bank_Location, adjust = "tukey")

emmip(lmer_gaus_fg_4, FunctionalGroup2 ~ Bank_Location, CIs = TRUE)

#customizations
emmip(lmer_gaus_fg_4, FunctionalGroup2 ~ Bank_Location, CIs = TRUE, linearg = list(),
      CIarg = list(lwd = 1, alpha = 1)) +
  ggplot2::theme_bw() +
  ylab("Linear Prediction of Cover Functional Group Proportion") +       
  xlab("Bank Location") +
  ggtitle("Vegetation")

emmip(lmer_gaus_fg_4, FunctionalGroup2 ~ Bank_Location, linearg = list(),
      CIarg = list(lwd = 1, alpha = 1)) +
  ggplot2::theme_bw() +
  ylab("Linear Prediction of Cover Functional Group Proportion") +       
  xlab("Bank Location") +
  ggtitle("Vegetation")
```




```{r graph common species using both sample bouts}

#This csv contains both sampling bouts and first and second hits

Common_species_BothBouts <- read.csv("C:/Users/Christina.Alba/.ssh/HLC_soil_and_veg/Common_species_props_upload_BothBouts.csv")

str(Common_species_BothBouts)
View(Common_species_BothBouts)

#Remove unwanted columns and change to long format

Common_species_BothBouts <- select(Common_species_BothBouts, -Total.Hits, -Hit.by.loc)

Common_species_BothBouts_long <- melt(Common_species_BothBouts, id.vars = c("Baseline","Transect", "Location"))

View(Common_species_BothBouts_long)


Common_species_BothBouts_long %>% ggplot(aes(x=variable, y=value))+
  geom_boxplot()+
  geom_point()+

  labs(x = "Species", y = "Proportion of Cover")+
  theme_bw(base_size = 16)

#Need to get the means of each baseline
#The above code currently graphs all 45 transects

df_commonSpp_baseline_means <- Common_species_BothBouts_long %>%
  group_by(Baseline, variable) %>%
  dplyr::summarise(Mean = mean(value))

View(df_commonSpp_baseline_means)


#Now create new boxplot with baseline means

df_commonSpp_baseline_means %>% ggplot(aes(x=variable, y=Mean))+
  geom_boxplot()+
  geom_point()+

  labs(x = "Species", y = "Proportion of Cover")+
  stat_summary(fun=mean, geom="point", aes(group = variable), position = position_dodge(.9), shape=20, size=2.5, color="red", fill="red")+
  theme_bw(base_size = 16)+
  theme(axis.text.x=element_text(angle=90, hjust=1))


#Now get the means of each species by bank location

df_commonSpp_bankLoc_means <- Common_species_BothBouts_long %>%
  group_by(Baseline, Location, variable) %>%
  dplyr::summarise(Mean = mean(value))

View(df_commonSpp_bankLoc_means)

#Now create new boxplot with baseline means by bank location

p <- df_commonSpp_bankLoc_means %>% ggplot(aes(x=variable, y=Mean))+
  geom_boxplot()+
  geom_point()+

  labs(x = "Species", y = "Proportion of Cover")+
  stat_summary(fun=mean, geom="point", aes(group = variable), position = position_dodge(.9), shape=20, size=2.5, color="red", fill="red")+
  theme_bw(base_size = 16)+
  theme(axis.text.x=element_text(angle=90, hjust=1))

print(p)

p + facet_wrap(~Location)


#Add code that reorders from highest to lowest cover
#Not working yet, don't know why

p <- df_commonSpp_bankLoc_means %>% ggplot(aes(x=fct_reorder(variable,Mean,mean), y=Mean))+
  geom_boxplot()+
  geom_point()+

  labs(x = "Species", y = "Proportion of Cover")+
  stat_summary(fun=mean, geom="point", aes(group = variable), position = position_dodge(.9), shape=20, size=2.5, color="red", fill="red")+
  theme_bw(base_size = 16)+
  theme(axis.text.x=element_text(angle=90, hjust=1))

print(p)

p + facet_wrap(~Location)


```

```{r graph common species using only first sample bout}

#This csv contains only first sampling bout and first and second hits

Common_species_FirstBout <- read.csv("C:/Users/Christina.Alba/.ssh/HLC_soil_and_veg/Common_species_props_upload_FirstBout.csv")

str(Common_species_FirstBout)
View(Common_species_FirstBout)

#Remove unwanted columns and change to long format

Common_species_FirstBout <- select(Common_species_FirstBout, -Total.Hits, -Hit.by.Loc, -caremo, -elyrep, -conarv, -broine, -cirarv, -phaaru, 
                                   -taroff, -dacglo, -symlan, -symocc, -brotec, -rhacat, -medsat, -pruvir, -rumcri, -scharu)

Common_species_FirstBout_long <- melt(Common_species_FirstBout, id.vars = c("Baseline","Transect", "Location"))

View(Common_species_FirstBout_long)


Common_species_FirstBout_long %>% ggplot(aes(x=variable, y=value))+
  geom_boxplot()+
  geom_point()+

  labs(x = "Species", y = "Proportion of Cover")+
  theme_bw(base_size = 16)

#Need to get the means of each baseline
#The above code currently graphs all 45 transects

df_commonSpp_baseline_means <- Common_species_FirstBout_long %>%
  group_by(Baseline, variable) %>%
  dplyr::summarise(Mean = mean(value))

View(df_commonSpp_baseline_means)


#Now create new boxplot with baseline means

df_commonSpp_baseline_means %>% ggplot(aes(x=variable, y=Mean))+
  geom_boxplot()+
  geom_point()+

  labs(x = "Species", y = "Proportion of Cover")+
  stat_summary(fun=mean, geom="point", aes(group = variable), position = position_dodge(.9), shape=20, size=2.5, color="red", fill="red")+
  theme_bw(base_size = 16)+
  theme(axis.text.x=element_text(angle=90, hjust=1))


#Now get the means of each species by bank location

df_commonSpp_bankLoc_means <- Common_species_FirstBout_long %>%
  group_by(Baseline, Location, variable) %>%
  dplyr::summarise(Mean = mean(value))

View(df_commonSpp_bankLoc_means)

#Now create new boxplot with baseline means by bank location

p <- df_commonSpp_bankLoc_means %>% ggplot(aes(x=variable, y=Mean))+
  geom_boxplot()+
  geom_point()+

  labs(x = "Species", y = "Proportion of Cover")+
  stat_summary(fun=mean, geom="point", aes(group = variable), position = position_dodge(.9), shape=20, size=2.5, color="red", fill="red")+
  theme_bw(base_size = 16)+
  theme(axis.text.x=element_text(angle=90, hjust=1))

print(p)

p + facet_wrap(~Location) 


#Now reorder by descending order of cover within each panel
#Not working can't figure it out

str(df_commonSpp_bankLoc_means)


df_commonSpp_bankLoc_means %>% 
  ggplot(aes(y=reorder_within(Mean, variable, Location), 
              x=variable)) +
  geom_boxplot()+
  geom_point()+
  scale_y_reordered()+
  facet_wrap(~Location, scales = "free_y")+

  labs(x = "Species", y = "Proportion of Cover")+
  stat_summary(fun=mean, geom="point", aes(group = variable), position = position_dodge(.9), shape=20, size=2.5, color="red", fill="red")+
  theme_bw(base_size = 16)+
  theme(axis.text.x=element_text(angle=90, hjust=1))


```

```{r graph ground cover}

#This csv contains both sampling bouts
#Based on graphing, this way of looking at it is not too informative; need to combine ground cover and foliar cover to
#get a feel for bank locations with veg cover versus none

Ground_cover <- read.csv("C:/Users/Christina.Alba/.ssh/HLC_soil_and_veg/Ground_coverProps_upload.csv")

str(Ground_cover)
View(Ground_cover)

#Remove unwanted columns and change to long format

Ground_cover <- select(Ground_cover, -Total.Hits, -Hit.by.Loc, -Bare, -Litter, -WoodDebris, -Water, -Rock, -Prop.Water, -Prop.Rock)

Ground_cover_long <- melt(Ground_cover, id.vars = c("Baseline","Transect", "Location"))

View(Ground_cover_long)


Ground_cover_long %>% ggplot(aes(x=variable, y=value))+
  geom_boxplot()+
  geom_point()+

  labs(x = "Cover Type", y = "Proportion of Cover")+
  theme_bw(base_size = 16)


#Need to get the means of each baseline
#The above code currently graphs all 45 transects

df_GroundCover_baseline_means <- Ground_cover_long %>%
  group_by(Baseline, Location, variable) %>%
  dplyr::summarise(Mean = mean(value))

View(df_GroundCover_baseline_means)


#Now create new boxplot with baseline means by bank location

p <- df_GroundCover_baseline_means %>% ggplot(aes(x=variable, y=Mean))+
  geom_boxplot()+
  geom_point()+

  labs(x = "Cover Type", y = "Proportion of Cover")+
  stat_summary(fun=mean, geom="point", aes(group = variable), position = position_dodge(.9), shape=20, size=2.5, color="red", fill="red")+
  theme_bw(base_size = 16)+
  theme(axis.text.x=element_text(angle=90, hjust=1))

print(p)

p + facet_wrap(~Location)

```

