<<<<<<< HEAD
---
title: "HLC_Veg_Analysis"
author: "Christina Alba"
date: "1/14/2022"
output: html_document
---

```{r libraries, bring in file, some cleaning}

library(knitr); library(multcomp); library(dplyr);library(lme4);library(ggplot2); library(tidyverse); library(ggpubr); library(rstatix);library(writexl);library(ggformula); library(tidyr);library(reshape2)

#Bring in raw data file
veg <- read.csv("Q:/Research/Grants and Funding/HighLineCanalConservancy_2019/7_Project/Stormwater_MovedToQ_UseMe/Data_Analysis/vegetation/Raw Data from RickL/20201204_allHitsData_postQC_prep4.csv")

#Check: do we need to add Alissa's home computer location to bring in raw data file

head(veg)
str(veg)

View(veg)

#change sample bout to a factor

veg <- veg %>%
  mutate(sample.bout = as.factor(sample.bout))%>%
  mutate(baseline.rep = as.factor(baseline.rep))

str(veg)

## Remove zero from Hit.Number

veg <- veg[veg$Hit.Number != "0",]
View(veg)

#Rename unwieldly columns; remove unwanted columns
vegdf <- veg %>% select(-Number.of.Points.Along.Transect_fromRick) %>%
rename(Num_transect_points = Number.of.points.along.transect_ChrissyCalc)

head(vegdf)
View(vegdf)


```


```{r count hits at each level of organization: canal, baseline, transect}

#Summing number of hits at each level of organization (whole canal, baselines, transects)

#Whole-canal level: number of species hits by sample bout and hit number, includes foliar and ground first hits
df.canal <- vegdf %>% 
  group_by(sample.bout, Hit.Number) %>%
  summarise(Species.Hit = n()) 

View(df.canal)
write_xlsx(df.canal, 'hits_byCanal.xlsx')

#Baseline level: number of species hits by sample bout and hit number, includes foliar and ground first hits
df.baseline <- vegdf %>% 
  group_by(sample.bout, baseline, Hit.Number) %>%
  summarise(Species.Hit = n()) 

View(df.baseline)

write_xlsx(df.baseline, 'hits_byBaseline.xlsx')

#Transect level: number of species hits by sample bout and hit number, includes foliar and ground first hits

df.transect <- vegdf %>% 
  group_by(sample.bout, baseline, baseline.rep, Hit.Number) %>%
  summarise(Species.Hit = n()) 

View(df.transect)

write_xlsx(df.transect, 'hits_byTransect.xlsx')

```


```{r species hits exploration}

#Foliar hits only
#Group species counts by sample bout, hit number, transect, etc.
#Use summarise to count hits by species, drop NA's

veg_only_transect <- vegdf %>%
  group_by(sample.bout, Hit.Number, baseline, Transect, Num_transect_points, Bank_Location, FunctionalGroup, Nativity, Cvalue, WIS, Species.Hit) %>%
  summarise(Species = n()) %>%
  drop_na()

head(veg_only_transect)
View(veg_only_transect)

#The Excel file exported below has both sample bouts

write_xlsx(veg_only_transect, 'Species_counts.xlsx')

#Foliar hits only
#summarize species proportions at scale of whole canal, includes all sample bouts and hits
#Used sum(prop_species$Freq) code to count 1909 total hits across whole canal
#Use to determine which species have at least 1% cover
#To see all species, remove the filter statement

prop_species_canal <- veg_only_transect %>%
  group_by(Species.Hit) %>%
  summarise(Freq = sum(Species)) %>%
  mutate(prop = Freq/1909) %>%
  filter(prop > 0.0099) %>%
  arrange(desc(prop))
  
View(prop_species_canal)

sum(prop_species_canal$Freq)

#Now filter out species with 1% as shown from the above

Common_species_canal <- veg_only_transect %>%
  group_by(baseline) %>%
  filter(Species.Hit == "Bromus inermis"| Species.Hit == "Phalaris arundinacea" | Species.Hit == "Elymus repens"
         | Species.Hit == "Convolvulus arvensis" | Species.Hit == "Cirsium arvense" | Species.Hit == "Dactylis glomerata"
         | Species.Hit == "	Carex emoryi" | Species.Hit == "Rhamnus cathartica" | Species.Hit == "Symphyotrichum lanceolatum ssp. hesperium"
         | Species.Hit == "Taraxacum officinale" | Species.Hit == "Schedonorus arundinaceus" | Species.Hit == "Symphoricarpos occidentalis"
         | Species.Hit == "Salix exigua ssp. exigua" | Species.Hit == "Medicago sativa" | Species.Hit == "Typha angustifolia"
         | Species.Hit == "Ulmus pumila" | Species.Hit == "Bromus tectorum") 
  
  
View(Common_species_canal)

#The Excel file exported below has both sample bouts

write_xlsx(Common_species_canal, 'Common_species_counts.xlsx')


#Same as above but look at only first sample bout 

veg_only_transect_firstOnly <- filter(veg_only_transect, sample.bout == "1")
View(veg_only_transect_firstOnly)


prop_species_canal_firstOnly <- veg_only_transect_firstOnly %>%
  group_by(Species.Hit) %>%
  summarise(Freq = sum(Species)) %>%
  mutate(prop = Freq/631) %>%
  filter(prop > 0.0099) %>%
  arrange(desc(prop))

View(prop_species_canal_firstOnly)

sum(prop_species_canal_firstOnly$Species)


#Same as above but look at only second sample bout 

veg_only_transect_secondOnly <- filter(veg_only_transect, sample.bout == "2")
View(veg_only_transect_secondOnly)


prop_species_canal_secondOnly <- veg_only_transect_secondOnly %>%
  group_by(Species.Hit) %>%
  summarise(Freq = sum(Species)) %>%
  mutate(prop = Freq/1052) %>%
  filter(prop > 0.0099) %>%
  arrange(desc(prop))

View(prop_species_canal_secondOnly)

sum(veg_only_transect_secondOnly$Species)


#Foliar hits only
#Use most common species determined above and group by bank location and baseline, includes all sample bouts and hits

prop_bank <- veg_only_transect %>%
  group_by(Species.Hit, Bank_Location) %>%
  summarise(Freq = sum(Species))

View(prop_bank)

sum(prop_bank$Freq)

#Foliar hits only
#Use the code below to create a data set where we have a list
#of each species that occurs in the upper/middle/lower banks
#Then can look at the proportion of native and intro species present that are 
#grouped into the various functional/WIS groups #Thinking we will find
#that native/intro differently distributed across the bank gradient and
#native/intro do different "jobs" based on their functional group and WIS
#Maybe use a percentage bar chart to show groups of native/intro
#by upper middle lower banks

#REDO BELOW AFTER FIRST SELECTING FOR ONLY THE FIRST SAMPLE BOUT AND FIRST HIT

prop_species_bank <- veg_only_transect %>%
  group_by(Species.Hit, Bank_Location, FunctionalGroup, Nativity, WIS) %>%
  summarise(Freq = sum(Species))

View(prop_species_bank)

#Distinct species presence by bank location

distinct_species_bank <- prop_species_bank %>%
  distinct(Bank_Location, FunctionalGroup, Nativity, WIS)%>%
  arrange(desc(Bank_Location))

View(distinct_species_bank)

```


```{r ground hits exploration}

#Ground hits only
#Group species counts by sample bout, hit number, transect, etc.
#Use summarise to count hits by species, drop NA's

ground_only_transect <- vegdf %>%
  group_by(sample.bout, Hit.Number, Bank_Location, baseline, Transect, Num_transect_points, Transect.Point.Soil.Surface) %>%
  summarise(Ground = n()) %>%
  drop_na()

head(ground_only_transect)
View(ground_only_transect)

write_xlsx(ground_only_transect, 'Ground_counts.xlsx')

getwd()

#summarize ground hit proportions at scale of whole canal, includes all sample bouts and hits
#Used sum(prop_ground$Freq) code to count 4664 total hits

prop_ground <- ground_only_transect %>%
  group_by(Transect.Point.Soil.Surface) %>%
  summarise(Freq = sum(Ground)) %>%
  mutate(prop = Freq/4664)
  
View(prop_ground)

sum(prop_ground$Freq)

```


```{r graph WIS by baseline}

WIS_baseline <- read.csv("C:/Users/Christina.Alba/.ssh/HLC_soil_and_veg/WIS_baseline_upload.csv")

str(WIS_baseline)
View(WIS_baseline)

#Remove unwanted columns and change to long format

WIS_baseline <- select(WIS_baseline, -Total.Hits, - UPL, -FACU, -FAC, -FACW, -OBL)

WIS_baseline_long <- melt(WIS_baseline, id.vars = c("Baseline","Transect"))

View(WIS_baseline_long)

#add data points w/o jitter 
#Facet by WIS type

WIS_baseline_long %>% ggplot(aes(x=Baseline, y=value)) +
  geom_boxplot()+
  geom_point()+
  theme_bw(base_size=16)+
  facet_wrap(~variable)

#add data points w/o jitter
#Facet by Baseline

WIS_baseline_long %>% ggplot(aes(x=variable, y=value)) +
  geom_boxplot()+
  geom_point()+
  theme_bw(base_size=16)+
  facet_wrap(~Baseline)

#add data points w/o jitter
#Not faceted by baseline; includes all 45 transects

WIS_baseline_long %>% ggplot(aes(x=variable, y=value)) +
  geom_boxplot()+
  geom_point()+
  theme_bw(base_size=16)

#Need to get the means of each baseline

df_WIS_baseline_means <- WIS_baseline_long %>%
  group_by(Baseline, variable) %>%
  dplyr::summarise(Mean = mean(value))

View(df_WIS_baseline_means)

#Now do boxplot 

df_WIS_baseline_means %>% ggplot(aes(x=variable, y=Mean)) +
  geom_boxplot()+
  geom_point()+
  theme_bw(base_size=16)

```


```{r graph WIS by bank location}

#This csv contains only first sampling bout and first hits

WIS_bankLoc <- read.csv("C:/Users/Christina.Alba/.ssh/HLC_soil_and_veg/WIS_byBankLoc_Upload.csv")

str(WIS_bankLoc)
View(WIS_bankLoc)

#Remove unwanted columns and change to long format

WIS_bankLoc <- select(WIS_bankLoc, -Total.Hits, -Hits.by.Loc, - UPL, -FACU, -FAC, -FACW, -OBL)

WIS_bankLoc_long <- melt(WIS_bankLoc, id.vars = c("Baseline","Transect", "Location"))

View(WIS_bankLoc_long)

 
#add data points w/o jitter for bank location
#change width of boxes and add axis labels 
#Visualize boxplots and can see that the level of replication being graphed is wrong
#b/c it is showing all 45 transects


p <- WIS_bankLoc_long %>% ggplot(aes(x=variable, y=value))+
  geom_boxplot()+
  geom_point()+

  labs(x = "Wetland Indicator Status", y = "Proportion")+
  theme_bw(base_size = 16)
print(p)

p + facet_wrap(~Location)

#Need to get the means of each baseline
#The above code currently graphs all 45 transects

df_WIS_baseline_means <- WIS_bankLoc_long %>%
  group_by(Baseline, Location, variable) %>%
  dplyr::summarise(Mean = mean(value))

View(df_WIS_baseline_means)

#Now create new boxplot with baseline means

p <- df_WIS_baseline_means %>% ggplot(aes(x=variable, y=Mean))+
  geom_boxplot()+
  geom_point()+

  labs(x = "Wetland Indicator Status", y = "Proportion")+
  stat_summary(fun=mean, geom="point", aes(group = variable), position = position_dodge(.9), shape=20, size=2.5, color="red", fill="red")+
  theme_bw(base_size = 16)+
  theme(axis.text.x=element_text(angle=90, hjust=1))

print(p)

p + facet_wrap(~Location)

```


```{r graph native/intro by bank location}

#This csv contains only first sampling bout and first hits

NatIntro_bankLoc <- read.csv("C:/Users/Christina.Alba/.ssh/HLC_soil_and_veg/NativeIntro_byBankLoc_Upload.csv")

str(NatIntro_bankLoc)
View(NatIntro_bankLoc)

#Remove unwanted columns 

NatIntro_bankLoc <- select(NatIntro_bankLoc, -Total.Hits, -Hits.by.Loc, - Native, -Introduced)

View(NatIntro_bankLoc)

#add data points w/o jitter for bank location
#change width of boxes and add axis labels 
#Visualize boxplots and can see that the level of replication being graphed is wrong
#b/c it is showing all 45 transects


NatIntro_bankLoc %>% ggplot(aes(x=Location, y=Prop.native))+
  geom_boxplot()+
  geom_point()+

  labs(x = "Bank Location", y = "Proportion of Cover")+
  stat_summary(fun=mean, geom="point", aes(group = Location), position = position_dodge(.9), shape=20, size=2.5, color="red", fill="red")+
  theme_bw(base_size = 16)


#Need to get the means of each baseline
#The above code currently graphs all 45 transects

df_NatIntro_baseline_means <- NatIntro_bankLoc %>%
  group_by(Baseline, Location) %>%
  dplyr::summarise(Mean = mean(Prop.native))

View(df_NatIntro_baseline_means)


#Now create new boxplot with baseline means averaging over bank location

NatIntro_bankLoc %>% ggplot(aes(x=fct_reorder(Baseline, Prop.native, mean, .desc = TRUE), y =Prop.native))+
  geom_boxplot()+
  geom_point()+

  labs(x = "Baseline", y = "Proportion of Native Cover")+
  stat_summary(fun=mean, geom="point", aes(group = Baseline), position = position_dodge(.9), shape=20, size=2.5, color="red", fill="red")+
  theme_bw(base_size = 16)


#Now create boxplot that looks at baseline x bank location

NatIntro_bankLoc %>% ggplot(aes(x=fct_reorder(Baseline, Prop.native, mean, .desc = TRUE), y =Prop.native, color=Location))+
  geom_boxplot(width = 0.5)+
  geom_point()+

  labs(x = "Baseline", y = "Proportion of Native Cover", color = "Bank Location")+
  stat_summary(fun=mean, geom="point", aes(group = Baseline), position = position_dodge(.9), shape=20, size=2.5, color="red", fill="red")+
  theme_bw(base_size = 16)

```


```{r graph common species}

#This csv contains both sampling bouts

Common_species <- read.csv("C:/Users/Christina.Alba/.ssh/HLC_soil_and_veg/Common_species_props_upload.csv")

str(Common_species)
View(Common_species)

#Remove unwanted columns and change to long format

Common_species <- select(Common_species, -Total.Hits, -Hit.by.loc)

Common_species_long <- melt(Common_species, id.vars = c("Baseline","Transect", "Location"))

View(Common_species_long)


Common_species_long %>% ggplot(aes(x=variable, y=value))+
  geom_boxplot()+
  geom_point()+

  labs(x = "Species", y = "Proportion of Cover")+
  theme_bw(base_size = 16)

#Need to get the means of each baseline
#The above code currently graphs all 45 transects

df_commonSpp_baseline_means <- Common_species_long %>%
  group_by(Baseline, variable) %>%
  dplyr::summarise(Mean = mean(value))

View(df_commonSpp_baseline_means)


#Now create new boxplot with baseline means

df_commonSpp_baseline_means %>% ggplot(aes(x=variable, y=Mean))+
  geom_boxplot()+
  geom_point()+

  labs(x = "Species", y = "Proportion of Cover")+
  stat_summary(fun=mean, geom="point", aes(group = variable), position = position_dodge(.9), shape=20, size=2.5, color="red", fill="red")+
  theme_bw(base_size = 16)+
  theme(axis.text.x=element_text(angle=90, hjust=1))



#Now get the means of each species by bank location

df_commonSpp_bankLoc_means <- Common_species_long %>%
  group_by(Baseline, Location, variable) %>%
  dplyr::summarise(Mean = mean(value))

View(df_commonSpp_bankLoc_means)

#Now create new boxplot with baseline means by bank location

p <- df_commonSpp_bankLoc_means %>% ggplot(aes(x=variable, y=Mean))+
  geom_boxplot()+
  geom_point()+

  labs(x = "Species", y = "Proportion of Cover")+
  stat_summary(fun=mean, geom="point", aes(group = variable), position = position_dodge(.9), shape=20, size=2.5, color="red", fill="red")+
  theme_bw(base_size = 16)+
  theme(axis.text.x=element_text(angle=90, hjust=1))

print(p)

p + facet_wrap(~Location)


#Add code that reorders from highest to lowest cover
#Not working yet, don't know why

p <- df_commonSpp_bankLoc_means %>% ggplot(aes(x=fct_reorder(variable,Mean,mean), y=Mean))+
  geom_boxplot()+
  geom_point()+

  labs(x = "Species", y = "Proportion of Cover")+
  stat_summary(fun=mean, geom="point", aes(group = variable), position = position_dodge(.9), shape=20, size=2.5, color="red", fill="red")+
  theme_bw(base_size = 16)+
  theme(axis.text.x=element_text(angle=90, hjust=1))

print(p)

p + facet_wrap(~Location)


```


```{r graph ground cover}

#This csv contains both sampling bouts

Ground_cover <- read.csv("C:/Users/Christina.Alba/.ssh/HLC_soil_and_veg/Ground_coverProps_upload.csv")

str(Ground_cover)
View(Ground_cover)

#Remove unwanted columns and change to long format

Ground_cover <- select(Ground_cover, -Total.Hits, -Hit.by.Loc, -Bare, -Litter, -WoodDebris, -Water, -Rock, -Prop.Water, -Prop.Rock)

Ground_cover_long <- melt(Ground_cover, id.vars = c("Baseline","Transect", "Location"))

View(Ground_cover_long)


Ground_cover_long %>% ggplot(aes(x=variable, y=value))+
  geom_boxplot()+
  geom_point()+

  labs(x = "Cover Type", y = "Proportion of Cover")+
  theme_bw(base_size = 16)


#Need to get the means of each baseline
#The above code currently graphs all 45 transects

df_GroundCover_baseline_means <- Ground_cover_long %>%
  group_by(Baseline, Location, variable) %>%
  dplyr::summarise(Mean = mean(value))

View(df_GroundCover_baseline_means)


#Now create new boxplot with baseline means by bank location

p <- df_GroundCover_baseline_means %>% ggplot(aes(x=variable, y=Mean))+
  geom_boxplot()+
  geom_point()+

  labs(x = "Cover Type", y = "Proportion of Cover")+
  stat_summary(fun=mean, geom="point", aes(group = variable), position = position_dodge(.9), shape=20, size=2.5, color="red", fill="red")+
  theme_bw(base_size = 16)+
  theme(axis.text.x=element_text(angle=90, hjust=1))

print(p)

p + facet_wrap(~Location)

```