---
title: "Chrissy_seedbank"
author: "Christina Alba"
date: "8/4/2022"
output: html_document
---

```{r bring in library and data file}

library(knitr); library(multcomp); library(dplyr);library(lme4);library(ggplot2); library(tidyverse); library(tidytext);
library(ggpubr); library(rstatix);library(writexl);library(ggformula); library(tidyr);library(reshape2); library(sjPlot); library(emmeans)


seedbank <- read.csv("Q:/Research/Grants and Funding/HighLineCanalConservancy_2019/7_Project/Stormwater_MovedToQ_UseMe/Data_Analysis/seedbank/20220802_HLC_SB_Data_Final4.csv")

head(seedbank)
str(seedbank)
View(seedbank)

#Remove unwanted columns
seedbankdf <- seedbank %>% select(c(-Specific.Epithet_wconservative.cf, -Org_trayID))

#changed name of column
seedbankdf <- seedbankdf %>% rename(c(Species_Name=SPECIFIC_EPITHET_FINAL, Germinant_ID_Number = Germinant.ID))

head(seedbankdf)
View(seedbankdf)

#check species spellings

df <- seedbankdf %>% distinct(Species_Name)
View(df)

```

```{r count germinants at each level of organization: canal, baseline, transect, bank location}

#Summing number of germinants at each level of organization (whole canal, baselines, transects)
#For whole canal, no need to group by anything

germinants.canal <- seedbankdf %>%
  summarise(Species.Name = n()) 

View(germinants.canal)
write_xlsx(germinants.canal, 'germinants_byCanal.xlsx')

#Germinants by baseline

germinants.baseline <- seedbankdf %>% 
  group_by(Baseline) %>%
  summarise(Species.Name = n()) 

View(germinants.baseline)

write_xlsx(germinants.baseline, 'germinants_byBaseline.xlsx')

#Germinants by transect

germinants.transect <- seedbankdf %>% 
  group_by(Transect_ID) %>%
  summarise(Species.Name = n()) 

View(germinants.transect)

write_xlsx(germinants.transect, 'germinants_bytransect.xlsx')

germinants.bankloc <- seedbankdf %>%
  group_by(Transect_ID, Bank_Location) %>%
  summarise(Species_Name = n())

View(germinants.bankloc)

```


```{r WIS}

#Prepping data to compute proportions
#By baseline and bank location

seedbank$WIS <- as.factor(seedbank$WIS)

df.props_WIS_seed <- seedbank %>%
  group_by(Baseline, Transect_ID, Bank_Location, WIS, Longevity_1, Habit, Functional_Group_1, Nativity) %>%
  drop_na(SPECIFIC_EPITHET_FINAL, WIS) %>%  ## drops rows with missing values NA in either SPECIFIC_EPITHET_FINAL or WIS
  summarise(SPECIFIC_EPITHET_FINAL = n()) %>%  ## from the group_by groupings, count the number 
  group_by(Baseline, Bank_Location, WIS) %>%
  summarise(SPECIFIC_EPITHET_FINAL = sum(SPECIFIC_EPITHET_FINAL)) %>%  ## groups by baseline and Bank_location to sum SPECIFIC_EPITHET_FINAL
  mutate(prop = SPECIFIC_EPITHET_FINAL/sum(SPECIFIC_EPITHET_FINAL)) %>% ## mutate the df by adding prop that is each #sp/total
  complete(WIS, fill = list(SPECIFIC_EPITHET_FINAL = 0, prop = 0)) ## keep all levels of factor and replace NA with zeros for both   SPECIFIC_EPITHET_FINAL and prop

# Check it adds to one with the 5 groups  
sum(df.props_WIS_seed$prop[1:5])
    
View(df.props_WIS_seed)

#Make boxplot

p <- df.props_WIS_seed %>% ggplot(aes(x=factor(WIS, levels = c('UPL', 'FACU', 'FAC', 'FACW', 'OBL', 'Juncus sp. (FACW-OBL)')), y=prop))+ 
  geom_boxplot()+
  geom_point()+

  labs(x = "Wetland Indicator Status", y = "Proportion of Seedbank")+
  stat_summary(fun=mean, geom="point", aes(group = WIS), position = position_dodge(.9), shape=20, size=2.5, color="red", fill="red")+
  theme_bw(base_size = 16)+
  theme(axis.text.x=element_text(angle=90, hjust=1))
print(p)

p + facet_wrap(~Bank_Location)


```