---
title: "Dissimilarity above below veg"
author: "Michelle DePrenger-Levin"
date: '2022-09-05'
output: html_document
---

```{r libraries}
library(vegan)
library(dplyr)
library(tidyr)
library(ggplot2)
```

Dummy data (don't use)
```{r}
Trans <- 1:9
bank <- c("low","mid","upp")
VegSoil <- c("veg","soil")

df <- expand.grid(Trans,bank,VegSoil)
names(df) <- c("Trans","bank","VegSoil")

df <- df %>%
  group_by(Trans, bank,VegSoil) %>%
  dplyr::summarise(Sp1 = rbinom(n(), size = 1, prob = rbeta(1,1,1)),
                   Sp2 = rbinom(n(), size = 1, prob = rbeta(1,1,1)),
                   Sp3 = rbinom(n(), size = 1, prob = rbeta(1,1,1)),
                   Sp4 = rbinom(n(), size = 1, prob = rbeta(1,1,1)),
                   Sp5 = rbinom(n(), size = 1, prob = rbeta(1,1,1)),
                   Sp6 = rbinom(n(), size = 1, prob = rbeta(1,1,1)))

mds <- metaMDS(df[,-c(1:3)])
data.scores <- as.data.frame(scores(mds))
data.scores$Trans <- df$Trans
data.scores$bank <- df$bank
data.scores$VegSoil <- df$VegSoil

ggplot(data.scores, aes(NMDS1, NMDS2, colour = interaction(bank,VegSoil))) +
  geom_point()+
  stat_ellipse()+
  theme_bw()



braycurtis <- vegdist(df[,-c(1:3)])
as.dist(as.matrix(braycurtis)[df$bank =="low", df$bank == "low"])

## Rarefy and rarecurve for Rarefaction
spAbund <- rowSums(df[,-c(1:3)])
raremin <- min(rowSums(df[,-c(1:3)]))
sRare <- rarefy(df[,-c(1:3)], raremin)
rarecurve(df[,-c(1:3)])

# <https://peat-clark.github.io/BIO381/veganTutorial.html>

## mean within and between block dissimilarities
# diagonal values are mean dissimilarities within VegSoil and off-diagonal mean dissimilarities between different Veg and Soil 
meandist(braycurtis, grouping = df$VegSoil)

# look at differences in number of species
designdist(df[,-c(1:3)], "A-B", "binary")

# row-wise statistics like Shannon-Weaver diversity index
H <- diversity(df[,-c(1:3)]) # can be "simpson" or others
outer(H,H,"-")

## Analysis of variance using distance matrices, partition matrices among sources of variation and fitting linear models
?adonis

ad1 <- adonis(braycurtis ~ bank + VegSoil, data = df)
ad1


```

Convert above ground and soil seed bank data to wide for dissimilarity / also don't use
```{r - michelle's code for data wrangling with some edits}

#seperating transects
SB_transects <- distinct(seedbank, Full_TrayID , .keep_all = TRUE) %>%
  arrange(Full_TrayID) #81 or 27 if you change it to Transects
view(SB_transects)

VEG_transects <- distinct(aboveground, Transect, .keep_all = TRUE) %>%
  arrange(Transect) #45
view(VEG_transects)

# 1. read in data that is in long format
seedbank <- read.csv("20220802_HLC_SB_Data_Final4.csv") #mac path & Turquoise path

aboveground <- read.csv("20201204_allHitsData_postQC_prep4.csv") #mac

# 2. convert from long to wide
seedbank.wide <- seedbank %>%
  # If you want to remove not (!) when name contains sp., Unknown, or (|) cf. or if NA
  filter(!grepl("sp.|Unknown|cf.|NA",seedbank$SPECIFIC_EPITHET_FINAL),
         !is.na(SPECIFIC_EPITHET_FINAL)) %>%
  pivot_wider(id_cols = c("Full_TrayID"), # can add any other columns that add unique information to set
              names_from = "SPECIFIC_EPITHET_FINAL", # where names for columns come from
              values_from = "SPECIFIC_EPITHET_FINAL",
              values_fn = function(x) sum(!is.na(x)), values_fill = 0) # function to return a count of times the value appeared (and wasn't NA), fill in any others with 0
colnames(seedbank.wide) ## the first column (because only one id_cols) needs to be removed to make the dist matrix seedbank.wide[,-1]


aboveground.wide <- aboveground %>%
  filter(sample.bout == 1,  # you only wanted the first sampling bout
         !is.na(Species.Hit)) %>% # you can add to filter if you don't want the just genus ones 
  filter(Transect !="B10-12.5") %>% #filters to remove transects that were taken for veg but not sb
  filter(Transect !="B10-37.5") %>%
  filter(Transect !="B13-12.5") %>%
  filter(Transect !="B13-35.5") %>%
  filter(Transect !="B14-12.5") %>%
  filter(Transect !="B14-36.5") %>%
  filter(Transect !="B15-14") %>%
  filter(Transect !="B15-37.5") %>%
  filter(Transect !="B17-12.5") %>%
  filter(Transect !="B17-37.5") %>%
  filter(Transect !="B18-12.5") %>%
  filter(Transect !="B18-37.5") %>%
  filter(Transect !="B3-10") %>%
  filter(Transect !="B3-29") %>%
  filter(Transect !="B5-12.5") %>%
  filter(Transect !="B5-37.5") %>%
  filter(Transect !="B7-12.5") %>%
  filter(Transect !="B7-37.5") %>%
  pivot_wider(id_cols = c("Transect","baseline.rep","Bank_Location"), # Can add or remove from all the columns that unique identify a transect
              names_from = "Species.Hit",
              values_from = "Species.Hit",
              values_fn = function(x) sum(!is.na(x)), values_fill = 0)
colnames(aboveground.wide) ## Need to remove the first three columns aboveground.wide[,-c(1:3)]



# want all combined and want columns for all the species (or genera) across both
## i. need to make synonomous columns have the same column name 
## I'm assuming that SPECIFIC_EPITHET_FINAL == Species.Hit;
##                   Transect_ID == Transect
##                   Bank_Location == Bank_Location (yay! a sensical one)
## and that is enough. If you want to have WIS or Functional group or others, follow the same pattern
seedbank <- seedbank %>%
  dplyr::rename(Species.Hit = SPECIFIC_EPITHET_FINAL, ## new name = old name
         Transect = Transect_ID) %>%
  dplyr::mutate(VegSoil = "Soil")

aboveground.1 <- aboveground %>%
  filter(sample.bout == 1,  # you only wanted the first sampling bout
         !is.na(Species.Hit)) %>% # you can add to filter if you don't want the just genus ones 
  dplyr::mutate(VegSoil = "Veg")

species.wide <- bind_rows(seedbank[,c("Transect","Bank_Location","Species.Hit","VegSoil")],
                          aboveground.1[,c("Transect","Bank_Location","Species.Hit","VegSoil")]) %>%
  # filter(Transect %in% c(...list the transects you want for a specific comparison...), VegSoil = "Veg") %>% ## for whatever subsets you want for any given analysis
  pivot_wider(id_cols = c("Transect","VegSoil","Bank_Location"), # Can add or remove from all the columns that unique identify a transect
              names_from = "Species.Hit",
              values_from = "Species.Hit",
              values_fn = function(x) sum(!is.na(x)), values_fill = 0)
## need to remove the first three for vegdist(species.wide[,-c(1:3)]) 

## adjust as needed for whatever analysis you're doing. Keep the first three columns as a data.frame (or tibble) because you'll need them for group arguments



```

 START HERE 
```{r similarity data wrangling_START HERE}
# 1.  READ 

# read in data that is in long format
seedbank <- read.csv("20220802_HLC_SB_Data_Final5.csv") #mac path

aboveground <- read.csv("20201204_allHitsData_postQC_5.csv") #mac

str(seedbank)
distinct(seedbank, )

#2. APPLY FILTERS
#below code is the code that is excluding 19 samples (rows in the matrix)
seedbank.sim <- seedbank %>%
  # If you want to remove use not (!) when name contains sp., Unknown, or (|) cf. or if NA
  filter(!grepl("sp.|Unknown|cf.|NA",seedbank$SPECIFIC_EPITHET_FINAL), 
         !is.na(SPECIFIC_EPITHET_FINAL)) 
view(seedbank.sim)

aboveground.sim <- aboveground %>%
  filter(sample.bout == 1,  # only want the first sampling bout
         !is.na(Species.Hit)) %>% #  can add to filter if i don't want the just genus ones 
  filter(Transect !="B10-12.5") %>% #filters to remove transects that were taken for veg but not sb
  filter(Transect !="B10-37.5") %>%
  filter(Transect !="B13-12.5") %>%
  filter(Transect !="B13-35.5") %>%
  filter(Transect !="B14-12.5") %>%
  filter(Transect !="B14-36.5") %>%
  filter(Transect !="B15-14") %>%
  filter(Transect !="B15-37.5") %>%
  filter(Transect !="B17-12.5") %>%
  filter(Transect !="B17-37.5") %>%
  filter(Transect !="B18-12.5") %>%
  filter(Transect !="B18-37.5") %>%
  filter(Transect !="B3-10") %>%
  filter(Transect !="B3-29") %>%
  filter(Transect !="B5-12.5") %>%
  filter(Transect !="B5-37.5") %>%
  filter(Transect !="B7-12.5") %>%
  filter(Transect !="B7-37.5")

View(seedbank.sim)
View(aboveground.sim)

#  3. RENAME SO COLUMNS MATCH
seedbank.sim <- seedbank.sim %>%
  dplyr::rename(Species.Hit = SPECIFIC_EPITHET_FINAL, ## new name = old name
         Transect = Transect_ID) %>%
  dplyr::mutate(VegSoil = "Soil")

aboveground.sim <- aboveground.sim %>%
  filter(sample.bout == 1,  # only want the first sampling bout
         !is.na(Species.Hit)) %>% #  can add to filter if i don't want the just genus ones 
  dplyr::mutate(VegSoil = "Veg")

# 4. BIND & PIVOT

sim.matrix <- bind_rows(seedbank.sim[,c("Transect","Bank_Location","Species.Hit","VegSoil")],
                          aboveground.sim[,c("Transect","Bank_Location","Species.Hit","VegSoil")]) %>%
  # filter(Transect %in% c(...list the transects you want for a specific comparison...), VegSoil = "Veg") %>% ## for whatever subsets you want for any given analysis #<- that is note is from michelle. I feel like this would be helpful, but not sure how to go about it. 
  pivot_wider(id_cols = c("Transect","VegSoil","Bank_Location"), # Can add or remove from all the columns that unique identify a transect
              names_from = "Species.Hit",
              values_from = "Species.Hit",
              values_fn = function(x) sum(!is.na(x)), values_fill = 0)
## need to remove the first three for vegdist(species.wide[,-c(1:3)]) 

## adjust as needed for whatever analysis you're doing. Keep the first three columns as a data.frame (or tibble) because you'll need them for group arguments

View(sim.matrix) #why 143 rows? should be 162? 81*2

df <- seedbank %>% distinct(Org_trayID, Full_TrayID, Transect_ID, Bank_Location)
View(df)

df <- seedbank %>% distinct(Org_trayID, Full_TrayID, Transect_ID, Bank_Location)
View(df) #change to code sim.matix
```

``` {r similarity next steps} 

#reformatting so that we can see the transect/BL/veg or SB information on the edges rather than as a column, because the code to analyze the matrix requires no text data
sim.matrix$UniqueID <- paste(sim.matrix$Transect, sim.matrix$VegSoil, sim.matrix$Bank_Location, sep = "-") #pasting columns together

sim.matrix <- sim.matrix[,c(73,1:72)] #move uniqueID column to front
#should have new Unique ID column on far left; sometimes need to adjust this code if new columns are added

sim.matrix <- sim.matrix[order(sim.matrix$UniqueID),] #put in order

sim.matrix <- as.data.frame(sim.matrix) 

rownames(sim.matrix) <- sim.matrix$UniqueID

sim.matrix2 <- sim.matrix[-c(1:4)] #removing columns with text so that I can analyze

sim.matrix2 <- as.matrix(sim.matrix2)
head(sim.matrix2)
View(sim.matrix2)

#Running similarity
vegdist.out <- vegdist(sim.matrix2, method="bray", binary=TRUE) #Jaccard dissimilarity, presence/abs
matrix.out <- as.matrix(vegdist.out) #put into matrix 
View(matrix.out) #this is comparing all samples to each other #this is showing 143x143

#grabbing the numbers of interest from the matrix
DistVals <- data.frame(PlotID =NULL, Value = NULL) ## creating new dataframe to store outputs of plot dissimilarity 
for(i in 4:nrow(matrix.out)){ 
  wantRow <- row.names(matrix.out)[i] 
  wantCol <- row.names(matrix.out)[i-3]
  wantVal <- matrix.out[wantRow,wantCol]
  OutDF <- data.frame(PlotID = wantRow, Value = wantVal)
  DistVals <- rbind(DistVals, OutDF)
}

View(DistVals) #Giving me 140 rows

length(unique(DistVals$PlotID)) #should be 81; I think it is giving 140 because it's comparing soil to soil and veg to veg; If I figure out the initial issue (line 232) this issue might be easier to work out

#ideas -- could do some manual work --> pull numbers of interest out of matrix 
          # could filter one transect at a time (I think that's what michelle had in mind?)



```

```{r - similarity example}
Site = c("A", "B", "C", "D", "E", "F", "G", "H", "I", "J") 

PoolNumber = c(1, 3, 4, 2, 4, 1, 2, 3, 4, 4) 

Sp1 = c(3, 10, 7, 0, 12, 9, 4, 0, 4, 3) 

Sp2 = c(2, 1, 17, 1, 2, 9, 3, 1, 6, 7)

Sp3 = c(5, 12, 6, 10, 2, 4, 0, 1, 3, 3)

Sp4 = c(9, 6, 4, 8, 13, 5, 2, 20, 13, 3)

df = data.frame(Site, PoolNumber, Sp1, Sp2, Sp3, Sp4)


matrix <- df[,3:6]

braycurtis = vegdist(matrix, "bray")

hist(braycurtis)

braycurtis <- vegdist(df[,3:6])
as.matrix(braycurtis)[df$PoolNumber==4,df$PoolNumber==4]
as.dist(as.matrix(braycurtis)[df$PoolNumber==4,df$PoolNumber==4])

meandist(braycurtis, df$PoolNumber)

#sample code https://stackoverflow.com/questions/51200770/bray-curtis-pairwise-analysis-in-r

#above wasn't helpful. another example below


install.packages("betapart")
library(betapart)
comm <- read.csv(("communities.csv") ,row.names=1,sep=";")

groups <- factor(c(rep(1,3), rep(2,3)), labels = c("undisturbed","disturbed"))

presabs<-ifelse(comm>0,1,0)

dist<-beta.pair(presabs, index.family="jaccard")

bd<-betadisper(dist[[3]],groups)

plot(bd)

boxplot(bd)


```

